// ============================================================================
// SIMS Theme Data - All theme definitions in one place
// ============================================================================

// Base color keys that all themes must define
export const COLOR_KEYS = [
  '--bg-dark',
  '--bg-medium',
  '--bg-light',
  '--bg-card',
  '--bg-card-solid',
  '--primary',
  '--primary-light',
  '--primary-dark',
  '--accent1',
  '--accent2',
  '--accent3',
  '--status-available',
  '--status-checked-out',
  '--status-reserved',
  '--status-needs-attention',
  '--status-missing',
  '--condition-excellent',
  '--condition-good',
  '--condition-fair',
  '--condition-poor',
  '--text-primary',
  '--text-secondary',
  '--text-muted',
  '--border',
  '--border-light',
  '--danger',
  '--success',
  '--warning',
  '--on-primary',
  '--on-danger',
  '--on-success',
  '--focus-ring-color',
  '--focus-ring-color-danger',
  '--sidebar-item1',
  '--sidebar-item2',
  '--sidebar-item3',
  '--sidebar-item4',
  '--sidebar-item5',
  '--sidebar-item6',
  '--panel-stats',
  '--panel-search',
  '--panel-checkedout',
  '--panel-alerts',
  '--panel-reminders',
  '--panel-lowstock',
  '--panel-reservations',
  '--panel-maintenance',
  '--panel-activity',
  '--shadow-sm',
  '--shadow-md',
  '--shadow-lg',
  '--shadow-card',
];

// Color categories for the editor UI
export const COLOR_CATEGORIES = {
  backgrounds: {
    label: 'Backgrounds',
    colors: [
      { key: '--bg-dark', label: 'Main Background' },
      { key: '--bg-medium', label: 'Medium Background' },
      { key: '--bg-light', label: 'Light Background' },
      { key: '--bg-card', label: 'Card Background' },
    ],
  },
  primary: {
    label: 'Primary Colors',
    colors: [
      { key: '--primary', label: 'Primary' },
      { key: '--primary-light', label: 'Primary Light' },
      { key: '--primary-dark', label: 'Primary Dark' },
    ],
  },
  accents: {
    label: 'Accent Colors',
    colors: [
      { key: '--accent1', label: 'Accent 1' },
      { key: '--accent2', label: 'Accent 2' },
      { key: '--accent3', label: 'Accent 3' },
    ],
  },
  text: {
    label: 'Text Colors',
    colors: [
      { key: '--text-primary', label: 'Primary Text' },
      { key: '--text-secondary', label: 'Secondary Text' },
      { key: '--text-muted', label: 'Muted Text' },
    ],
  },
  status: {
    label: 'Status Colors',
    colors: [
      { key: '--status-available', label: 'Available' },
      { key: '--status-checked-out', label: 'Checked Out' },
      { key: '--status-reserved', label: 'Reserved' },
      { key: '--status-needs-attention', label: 'Needs Attention' },
      { key: '--status-missing', label: 'Missing' },
    ],
  },
  feedback: {
    label: 'Feedback Colors',
    colors: [
      { key: '--danger', label: 'Danger' },
      { key: '--success', label: 'Success' },
      { key: '--warning', label: 'Warning' },
    ],
  },
  accessibility: {
    label: 'Accessibility',
    colors: [
      { key: '--focus-ring-color', label: 'Focus Ring Color' },
      { key: '--focus-ring-color-danger', label: 'Focus Ring (Danger)' },
    ],
  },
  panels: {
    label: 'Dashboard Panels',
    colors: [
      { key: '--panel-stats', label: 'Statistics' },
      { key: '--panel-search', label: 'Quick Search' },
      { key: '--panel-checkedout', label: 'Checked Out' },
      { key: '--panel-alerts', label: 'Alerts' },
      { key: '--panel-reminders', label: 'Reminders' },
      { key: '--panel-lowstock', label: 'Low Stock' },
      { key: '--panel-reservations', label: 'Reservations' },
      { key: '--panel-maintenance', label: 'Maintenance' },
      { key: '--panel-activity', label: 'Recent Activity' },
    ],
  },
};

// Default custom theme (used as starting point for custom editor)
export const DEFAULT_CUSTOM_THEME = {
  '--bg-dark': '#1a1d21',
  '--bg-medium': '#22262b',
  '--bg-light': '#2a2f36',
  '--bg-card': '#22262b',
  '--bg-card-solid': '#22262b',
  '--primary': '#5d8aa8',
  '--primary-light': '#7ba3be',
  '--primary-dark': '#4a7089',
  '--accent1': '#6b9e9e',
  '--accent2': '#7a8f7a',
  '--accent3': '#8fa5b5',
  '--status-available': '#6b9e78',
  '--status-checked-out': '#8fa5b5',
  '--status-reserved': '#5d8aa8',
  '--status-needs-attention': '#b58f6b',
  '--status-missing': '#9e6b6b',
  '--condition-excellent': '#6b9e78',
  '--condition-good': '#7a8f7a',
  '--condition-fair': '#b5a56b',
  '--condition-poor': '#b58f6b',
  '--text-primary': '#e2e6ea',
  '--text-secondary': 'rgba(226, 230, 234, 0.65)',
  '--text-muted': 'rgba(226, 230, 234, 0.4)',
  '--border': 'rgba(93, 138, 168, 0.2)',
  '--border-light': 'rgba(93, 138, 168, 0.1)',
  '--danger': '#be7d7d', // brightened from #b56b6b for 4.5:1 error text on --bg-medium
  '--success': '#6b9e78',
  '--on-primary': '#ffffff',
  '--on-danger': '#ffffff',
  '--on-success': '#0b0d10',
  '--warning': '#b5a56b',
  '--focus-ring-color': '#8bb5cc',
  '--focus-ring-color-danger': '#d08080',
  '--sidebar-item1': '#5d8aa8',
  '--sidebar-item2': '#6b9e9e',
  '--sidebar-item3': '#7a8f7a',
  '--sidebar-item4': '#8fa5b5',
  '--sidebar-item5': '#a58f8f',
  '--sidebar-item6': '#9e9e6b',
  '--panel-stats': '#5d8aa8',
  '--panel-search': '#6b9e9e',
  '--panel-checkedout': '#8fa5b5',
  '--panel-alerts': '#b58f6b',
  '--panel-reminders': '#b5a56b',
  '--panel-lowstock': '#9e6b6b',
  '--panel-reservations': '#7a8f7a',
  '--panel-maintenance': '#a58f8f',
  '--panel-activity': '#8f7aa5',
  '--shadow-sm': '0 1px 2px rgba(0, 0, 0, 0.3)',
  '--shadow-md': '0 4px 6px rgba(0, 0, 0, 0.3)',
  '--shadow-lg': '0 10px 15px rgba(0, 0, 0, 0.3)',
  '--shadow-card': '0 4px 20px rgba(0, 0, 0, 0.25)',
};

// Helper to generate shadows
const shadow = (opacity = 0.3) => ({
  '--shadow-sm': `0 1px 2px rgba(0, 0, 0, ${opacity})`,
  '--shadow-md': `0 4px 6px rgba(0, 0, 0, ${opacity})`,
  '--shadow-lg': `0 10px 15px rgba(0, 0, 0, ${opacity})`,
  '--shadow-card': `0 4px 20px rgba(0, 0, 0, ${opacity - 0.05})`,
});

// ============================================================================
// Theme Definitions
// ============================================================================

export const themes = {
  light: {
    id: 'light',
    name: 'Light',
    description: 'Clean, standard light theme',
    colors: {
      '--bg-dark': '#f0f2f5',
      '--bg-medium': '#ffffff',
      '--bg-light': '#f8f9fa',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#2563eb',
      '--primary-light': '#3b82f6',
      '--primary-dark': '#1d4ed8',
      '--accent1': '#0891b2',
      '--accent2': '#059669',
      '--accent3': '#7c3aed',
      '--status-available': '#15803d',
      '--status-checked-out': '#2563eb',
      '--status-reserved': '#7c3aed',
      '--status-needs-attention': '#c2410c',
      '--status-missing': '#dc2626',
      '--condition-excellent': '#15803d',
      '--condition-good': '#16a34a',
      '--condition-fair': '#a16207',
      '--condition-poor': '#c2410c',
      '--text-primary': '#1f2937',
      '--text-secondary': '#4b5563',
      '--text-muted': '#636b74',
      '--border': '#e5e7eb',
      '--border-light': '#f3f4f6',
      '--danger': '#dc2626',
      '--success': '#15803d',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#a16207',
      '--sidebar-item1': '#2563eb',
      '--sidebar-item2': '#0891b2',
      '--sidebar-item3': '#059669',
      '--sidebar-item4': '#7c3aed',
      '--sidebar-item5': '#db2777',
      '--sidebar-item6': '#ea580c',
      '--panel-stats': '#2563eb',
      '--panel-search': '#0891b2',
      '--panel-checkedout': '#0d9488',
      '--panel-alerts': '#ea580c',
      '--panel-reminders': '#a16207',
      '--panel-lowstock': '#dc2626',
      '--panel-reservations': '#7c3aed',
      '--panel-maintenance': '#6366f1',
      '--panel-activity': '#059669',
      ...shadow(0.08),
    },
  },

  dark: {
    id: 'dark',
    name: 'Dark',
    description: 'Default dark theme with muted blue accents',
    colors: { ...DEFAULT_CUSTOM_THEME },
  },

  darker: {
    id: 'darker',
    name: 'Darker',
    description: 'Pure black backgrounds with grey accents',
    colors: {
      '--bg-dark': '#000000',
      '--bg-medium': '#0a0a0a',
      '--bg-light': '#141414',
      '--bg-card': '#0a0a0a',
      '--bg-card-solid': '#0a0a0a',
      '--primary': '#777777',
      '--primary-light': '#999999',
      '--primary-dark': '#555555',
      '--accent1': '#6e6e6e',
      '--accent2': '#777777',
      '--accent3': '#888888',
      '--status-available': '#6e6e6e',
      '--status-checked-out': '#777777',
      '--status-reserved': '#888888',
      '--status-needs-attention': '#999999',
      '--status-missing': '#aaaaaa',
      '--condition-excellent': '#6e6e6e',
      '--condition-good': '#777777',
      '--condition-fair': '#888888',
      '--condition-poor': '#999999',
      '--text-primary': '#aaaaaa',
      '--text-secondary': '#888888',
      '--text-muted': '#808080',
      '--border': '#333333',
      '--border-light': '#222222',
      '--danger': '#888888',
      '--success': '#6e6e6e',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#999999',
      '--sidebar-item1': '#777777',
      '--sidebar-item2': '#777777',
      '--sidebar-item3': '#777777',
      '--sidebar-item4': '#777777',
      '--sidebar-item5': '#777777',
      '--sidebar-item6': '#777777',
      '--panel-stats': '#555555',
      '--panel-search': '#555555',
      '--panel-checkedout': '#555555',
      '--panel-alerts': '#555555',
      '--panel-reminders': '#555555',
      '--panel-lowstock': '#555555',
      '--panel-reservations': '#555555',
      '--panel-maintenance': '#555555',
      '--panel-activity': '#555555',
      ...shadow(0.5),
    },
  },

  primaries: {
    id: 'primaries',
    name: 'Primaries',
    description: "Bright primary colors like children's toys",
    colors: {
      '--bg-dark': '#ffeb3b',
      '--bg-medium': '#fff59d',
      '--bg-light': '#fffde7',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#d32f2f',
      '--primary-light': '#e57373',
      '--primary-dark': '#b71c1c',
      '--accent1': '#1565c0',
      '--accent2': '#2e7d32',
      '--accent3': '#e65100',
      '--status-available': '#2e7d32',
      '--status-checked-out': '#1565c0',
      '--status-reserved': '#7b1fa2',
      '--status-needs-attention': '#bf360c',
      '--status-missing': '#c62828',
      '--condition-excellent': '#2e7d32',
      '--condition-good': '#558b2f',
      '--condition-fair': '#b86800',
      '--condition-poor': '#bf360c',
      '--text-primary': '#1a1a1a',
      '--text-secondary': '#333333',
      '--text-muted': '#666666',
      '--border': '#f44336',
      '--border-light': '#ffcdd2',
      '--danger': '#c62828',
      '--success': '#2e7d32',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#e65100',
      '--sidebar-item1': '#d32f2f',
      '--sidebar-item2': '#1565c0',
      '--sidebar-item3': '#2e7d32',
      '--sidebar-item4': '#e65100',
      '--sidebar-item5': '#7b1fa2',
      '--sidebar-item6': '#00838f',
      '--panel-stats': '#1565c0',
      '--panel-search': '#2e7d32',
      '--panel-checkedout': '#00838f',
      '--panel-alerts': '#e65100',
      '--panel-reminders': '#7b1fa2',
      '--panel-lowstock': '#c62828',
      '--panel-reservations': '#d32f2f',
      '--panel-maintenance': '#795548',
      '--panel-activity': '#558b2f',
      '--shadow-sm': '0 2px 4px rgba(244, 67, 54, 0.3)',
      '--shadow-md': '0 4px 8px rgba(33, 150, 243, 0.3)',
      '--shadow-lg': '0 10px 20px rgba(76, 175, 80, 0.3)',
      '--shadow-card': '0 4px 20px rgba(156, 39, 176, 0.25)',
    },
  },

  pastel: {
    id: 'pastel',
    name: 'Pastel',
    description: 'Soft, pleasing pastel tones',
    colors: {
      '--bg-dark': '#fdf2f8',
      '--bg-medium': '#fefefe',
      '--bg-light': '#f5f3ff',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#7c3aed',
      '--primary-light': '#8b5cf6',
      '--primary-dark': '#6d28d9',
      '--accent1': '#0891b2',
      '--accent2': '#059669',
      '--accent3': '#e11d48',
      '--status-available': '#059669',
      '--status-checked-out': '#2563eb',
      '--status-reserved': '#7c3aed',
      '--status-needs-attention': '#ea580c',
      '--status-missing': '#e11d48',
      '--condition-excellent': '#059669',
      '--condition-good': '#16a34a',
      '--condition-fair': '#8a6914',
      '--condition-poor': '#ea580c',
      '--text-primary': '#374151',
      '--text-secondary': '#4b5563',
      '--text-muted': '#636b74',
      '--border': '#e9d5ff',
      '--border-light': '#f3e8ff',
      '--danger': '#e11d48',
      '--success': '#059669',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#0b0d10',
      '--warning': '#8a6914',
      '--sidebar-item1': '#7c3aed',
      '--sidebar-item2': '#0891b2',
      '--sidebar-item3': '#059669',
      '--sidebar-item4': '#e11d48',
      '--sidebar-item5': '#ea580c',
      '--sidebar-item6': '#4f46e5',
      '--panel-stats': '#7c3aed',
      '--panel-search': '#0891b2',
      '--panel-checkedout': '#059669',
      '--panel-alerts': '#ea580c',
      '--panel-reminders': '#8a6914',
      '--panel-lowstock': '#e11d48',
      '--panel-reservations': '#4f46e5',
      '--panel-maintenance': '#6366f1',
      '--panel-activity': '#0d9488',
      ...shadow(0.1),
    },
  },

  terminal: {
    id: 'terminal',
    name: 'Terminal',
    description: '80s hacker computer aesthetic',
    colors: {
      '--bg-dark': '#0a0a0a',
      '--bg-medium': '#0d0d0d',
      '--bg-light': '#111111',
      '--bg-card': '#0d0d0d',
      '--bg-card-solid': '#0d0d0d',
      '--primary': '#00ff00',
      '--primary-light': '#33ff33',
      '--primary-dark': '#00cc00',
      '--accent1': '#00ff00',
      '--accent2': '#00dd00',
      '--accent3': '#00bb00',
      '--status-available': '#00ff00',
      '--status-checked-out': '#00cc00',
      '--status-reserved': '#00aa00',
      '--status-needs-attention': '#ffff00',
      '--status-missing': '#ff0000',
      '--condition-excellent': '#00ff00',
      '--condition-good': '#00dd00',
      '--condition-fair': '#ccff00',
      '--condition-poor': '#ffcc00',
      '--text-primary': '#00ff00',
      '--text-secondary': '#00cc00',
      '--text-muted': '#00a600', // brightened from #009900: must stay readable on the panel washes
      '--border': '#00ff00',
      '--border-light': '#004400',
      '--danger': '#ff0000',
      '--success': '#00ff00',
      '--on-primary': '#0b0d10',
      '--on-danger': '#ffffff',
      '--on-success': '#0b0d10',
      '--warning': '#ffff00',
      '--sidebar-item1': '#00ff00',
      '--sidebar-item2': '#00ff66',
      '--sidebar-item3': '#00ffaa',
      '--sidebar-item4': '#66ff00',
      '--sidebar-item5': '#00dd00',
      '--sidebar-item6': '#00cc00',
      /* Panel colors are used as 18–38% alpha washes BEHIND green text —
         they must stay deep and dark or the neon text drowns. Deep CRT-glow
         versions of the original neon hues: */
      '--panel-stats': '#006600',
      '--panel-search': '#006629',
      '--panel-checkedout': '#005e00',
      '--panel-alerts': '#666600',
      '--panel-reminders': '#006644',
      '--panel-lowstock': '#660000',
      '--panel-reservations': '#296600',
      '--panel-maintenance': '#005200',
      '--panel-activity': '#146614',
      '--shadow-sm': '0 0 5px rgba(0, 255, 0, 0.3)',
      '--shadow-md': '0 0 10px rgba(0, 255, 0, 0.3)',
      '--shadow-lg': '0 0 20px rgba(0, 255, 0, 0.3)',
      '--shadow-card': '0 0 15px rgba(0, 255, 0, 0.2)',
    },
    fontFamily: '"Courier New", Courier, monospace',
  },

  blackwhite: {
    id: 'blackwhite',
    name: 'Black & White',
    description: 'Pure grayscale aesthetic',
    colors: {
      '--bg-dark': '#ffffff',
      '--bg-medium': '#fafafa',
      '--bg-light': '#f5f5f5',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#333333',
      '--primary-light': '#555555',
      '--primary-dark': '#111111',
      '--accent1': '#444444',
      '--accent2': '#666666',
      '--accent3': '#888888',
      '--status-available': '#333333',
      '--status-checked-out': '#555555',
      '--status-reserved': '#777777',
      '--status-needs-attention': '#757575',
      '--status-missing': '#111111',
      '--condition-excellent': '#222222',
      '--condition-good': '#444444',
      '--condition-fair': '#777777',
      '--condition-poor': '#8d8d8d', // darkened from #999999 for 3:1 on the light card background
      '--text-primary': '#000000',
      '--text-secondary': '#333333',
      '--text-muted': '#6e6e6e',
      '--border': '#cccccc',
      '--border-light': '#eeeeee',
      '--danger': '#000000',
      '--success': '#333333',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#666666',
      '--sidebar-item1': '#333333',
      '--sidebar-item2': '#444444',
      '--sidebar-item3': '#555555',
      '--sidebar-item4': '#666666',
      '--sidebar-item5': '#777777',
      '--sidebar-item6': '#888888',
      '--panel-stats': '#333333',
      '--panel-search': '#555555',
      '--panel-checkedout': '#444444',
      '--panel-alerts': '#777777',
      '--panel-reminders': '#444444',
      '--panel-lowstock': '#222222',
      '--panel-reservations': '#666666',
      '--panel-maintenance': '#555555',
      '--panel-activity': '#333333',
      ...shadow(0.1),
    },
  },

  vibrant: {
    id: 'vibrant',
    name: 'Vibrant',
    description: 'Bold, saturated complementary colors',
    colors: {
      '--bg-dark': '#1a0a2e',
      '--bg-medium': '#16213e',
      '--bg-light': '#1f3460',
      '--bg-card': '#16213e',
      '--bg-card-solid': '#16213e',
      '--primary': '#ff006e',
      '--primary-light': '#ff4d94',
      '--primary-dark': '#cc0058',
      '--accent1': '#00f5d4',
      '--accent2': '#fee440',
      '--accent3': '#a46aeb',
      '--status-available': '#00f5d4',
      '--status-checked-out': '#00bbf9',
      '--status-reserved': '#a46aeb',
      '--status-needs-attention': '#fee440',
      '--status-missing': '#f15bb5',
      '--condition-excellent': '#00f5d4',
      '--condition-good': '#00bbf9',
      '--condition-fair': '#fee440',
      '--condition-poor': '#f15bb5',
      '--text-primary': '#ffffff',
      '--text-secondary': 'rgba(255, 255, 255, 0.8)',
      '--text-muted': 'rgba(255, 255, 255, 0.5)',
      '--border': 'rgba(255, 0, 110, 0.3)',
      '--border-light': 'rgba(255, 0, 110, 0.15)',
      '--danger': '#f15bb5',
      '--success': '#00f5d4',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#0b0d10',
      '--warning': '#fee440',
      '--sidebar-item1': '#ff006e',
      '--sidebar-item2': '#00f5d4',
      '--sidebar-item3': '#fee440',
      '--sidebar-item4': '#a46aeb',
      '--sidebar-item5': '#00bbf9',
      '--sidebar-item6': '#f15bb5',
      '--panel-stats': '#00f5d4',
      '--panel-search': '#00bbf9',
      '--panel-checkedout': '#a46aeb',
      '--panel-alerts': '#fee440',
      '--panel-reminders': '#00ff87',
      '--panel-lowstock': '#f15bb5',
      '--panel-reservations': '#ff006e',
      '--panel-maintenance': '#00bbf9',
      '--panel-activity': '#fee440',
      '--shadow-sm': '0 1px 3px rgba(255, 0, 110, 0.4)',
      '--shadow-md': '0 4px 8px rgba(0, 245, 212, 0.3)',
      '--shadow-lg': '0 10px 20px rgba(155, 93, 229, 0.3)',
      '--shadow-card': '0 4px 25px rgba(155, 93, 229, 0.4)',
    },
  },

  muted: {
    id: 'muted',
    name: 'Muted',
    description: 'Soft, desaturated tones',
    colors: {
      '--bg-dark': '#2d2d3a',
      '--bg-medium': '#363646',
      '--bg-light': '#404052',
      '--bg-card': '#363646',
      '--bg-card-solid': '#363646',
      '--primary': '#988088',
      '--primary-light': '#b8a1a8',
      '--primary-dark': '#6e5960',
      '--accent1': '#7ec8b8',
      '--accent2': '#c9b896',
      '--accent3': '#8b7eb8',
      '--status-available': '#7ec8b8',
      '--status-checked-out': '#7eb8c8',
      '--status-reserved': '#9b8ec8',
      '--status-needs-attention': '#c9b896',
      '--status-missing': '#b87e8b',
      '--condition-excellent': '#7ec8b8',
      '--condition-good': '#96c9a8',
      '--condition-fair': '#c9c196',
      '--condition-poor': '#c9a896',
      '--text-primary': '#e8e4e6',
      '--text-secondary': 'rgba(232, 228, 230, 0.7)',
      '--text-muted': 'rgba(232, 228, 230, 0.45)',
      '--border': 'rgba(157, 129, 137, 0.25)',
      '--border-light': 'rgba(157, 129, 137, 0.12)',
      '--danger': '#c595a0', // brightened from #b87e8b for 4.5:1 error text on --bg-medium
      '--danger-fill': '#b87e8b', // filled danger buttons keep the deeper rose (white label needs a dark fill)
      '--success': '#7ec8b8',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#0b0d10',
      '--warning': '#c9b896',
      '--sidebar-item1': '#ad919a',
      '--sidebar-item2': '#7ec8b8',
      '--sidebar-item3': '#c9b896',
      '--sidebar-item4': '#9b8ec8',
      '--sidebar-item5': '#7eb8c8',
      '--sidebar-item6': '#b87e8b',
      '--panel-stats': '#7ec8b8',
      '--panel-search': '#7eb8c8',
      '--panel-checkedout': '#96c9a8',
      '--panel-alerts': '#c9b896',
      '--panel-reminders': '#9b8ec8',
      '--panel-lowstock': '#b87e8b',
      '--panel-reservations': '#ad919a',
      '--panel-maintenance': '#c9a896',
      '--panel-activity': '#8b7eb8',
      ...shadow(0.25),
    },
  },

  xp: {
    id: 'xp',
    name: 'XP',
    description: 'Windows XP nostalgia',
    colors: {
      '--bg-dark': '#d4cdb8',
      '--bg-medium': '#ece9d8',
      '--bg-light': '#f5f4ea',
      '--bg-card': '#ece9d8',
      '--bg-card-solid': '#ece9d8',
      '--primary': '#003d99',
      '--primary-light': '#1f5faa',
      '--primary-dark': '#002266',
      '--accent1': '#1b7a1b',
      '--accent2': '#9e5000',
      '--accent3': '#990073',
      '--status-available': '#1b7a1b',
      '--status-checked-out': '#003d99',
      '--status-reserved': '#9e5000',
      '--status-needs-attention': '#9e5000',
      '--status-missing': '#a50000',
      '--condition-excellent': '#1b7a1b',
      '--condition-good': '#267326',
      '--condition-fair': '#8a6a00',
      '--condition-poor': '#9e5000',
      '--text-primary': '#222222',
      '--text-secondary': '#444444',
      '--text-muted': '#555555',
      '--border': '#b5ab90',
      '--border-light': '#d4d0c8',
      '--danger': '#a50000',
      '--success': '#1b7a1b',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#9e5000',
      '--sidebar-item1': '#003d99',
      '--sidebar-item2': '#1b7a1b',
      '--sidebar-item3': '#9e5000',
      '--sidebar-item4': '#990073',
      '--sidebar-item5': '#007399',
      '--sidebar-item6': '#7326bf',
      '--panel-stats': '#003d99',
      '--panel-search': '#1b7a1b',
      '--panel-checkedout': '#007399',
      '--panel-alerts': '#9e5000',
      '--panel-reminders': '#990073',
      '--panel-lowstock': '#a50000',
      '--panel-reservations': '#7326bf',
      '--panel-maintenance': '#9e5000',
      '--panel-activity': '#1b7a1b',
      '--shadow-sm': '1px 1px 0 #808080, inset 1px 1px 0 #ffffff',
      '--shadow-md': '2px 2px 0 #808080, inset 1px 1px 0 #ffffff',
      '--shadow-lg': '3px 3px 0 #808080, inset 1px 1px 0 #ffffff',
      '--shadow-card': '2px 2px 5px rgba(0, 0, 0, 0.3)',
    },
  },

  cheese: {
    id: 'cheese',
    name: 'Cheese',
    description: 'For the cheese enthusiasts 🧀',
    colors: {
      '--bg-dark': '#ffd54f',
      '--bg-medium': '#ffecb3',
      '--bg-light': '#fff8e1',
      '--bg-card': '#fffde7',
      '--bg-card-solid': '#fffde7',
      '--primary': '#bf360c',
      '--primary-light': '#e65100',
      '--primary-dark': '#8c2500',
      '--accent1': '#8d6e63',
      '--accent2': '#a1887f',
      '--accent3': '#bf360c',
      '--status-available': '#8d5600',
      '--status-checked-out': '#bf360c',
      '--status-reserved': '#8c2500',
      '--status-needs-attention': '#b33a00',
      '--status-missing': '#8c0000',
      '--condition-excellent': '#8d5600',
      '--condition-good': '#a06800',
      '--condition-fair': '#b33a00',
      '--condition-poor': '#8c0000',
      '--text-primary': '#4e342e',
      '--text-secondary': '#5d4037',
      '--text-muted': '#795548',
      '--border': '#d4a373',
      '--border-light': '#ffe0b2',
      '--danger': '#8c0000',
      '--success': '#8d5600',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#b33a00',
      '--sidebar-item1': '#bf360c',
      '--sidebar-item2': '#8d6e63',
      '--sidebar-item3': '#a1887f',
      '--sidebar-item4': '#795548',
      '--sidebar-item5': '#6d4c41',
      '--sidebar-item6': '#5d4037',
      '--panel-stats': '#bf360c',
      '--panel-search': '#8d6e63',
      '--panel-checkedout': '#a1887f',
      '--panel-alerts': '#b33a00',
      '--panel-reminders': '#795548',
      '--panel-lowstock': '#8c0000',
      '--panel-reservations': '#6d4c41',
      '--panel-maintenance': '#5d4037',
      '--panel-activity': '#8d5600',
      ...shadow(0.25),
    },
    backgroundImage: '/cheese-bg.svg',
    cursor: '/cheese-cursor.svg',
  },

  cats: {
    id: 'cats',
    name: 'Cats',
    description: 'Purrfect for cat lovers 🐱',
    colors: {
      '--bg-dark': '#fce4ec',
      '--bg-medium': '#fff0f5',
      '--bg-light': '#fff5f8',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#c2185b',
      '--primary-light': '#e91e63',
      '--primary-dark': '#880e4f',
      '--accent1': '#7b1fa2',
      '--accent2': '#512da8',
      '--accent3': '#1565c0',
      '--status-available': '#2e7d32',
      '--status-checked-out': '#1565c0',
      '--status-reserved': '#7b1fa2',
      '--status-needs-attention': '#e65100',
      '--status-missing': '#c62828',
      '--condition-excellent': '#2e7d32',
      '--condition-good': '#558b2f',
      '--condition-fair': '#b86800',
      '--condition-poor': '#e65100',
      '--text-primary': '#3e2723',
      '--text-secondary': '#4e342e',
      '--text-muted': '#795548',
      '--border': '#f8bbd9',
      '--border-light': '#fce4ec',
      '--danger': '#c62828',
      '--success': '#2e7d32',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#e65100',
      '--sidebar-item1': '#c2185b',
      '--sidebar-item2': '#7b1fa2',
      '--sidebar-item3': '#512da8',
      '--sidebar-item4': '#1565c0',
      '--sidebar-item5': '#d84315',
      '--sidebar-item6': '#2e7d32',
      '--panel-stats': '#c2185b',
      '--panel-search': '#7b1fa2',
      '--panel-checkedout': '#1565c0',
      '--panel-alerts': '#d84315',
      '--panel-reminders': '#512da8',
      '--panel-lowstock': '#c62828',
      '--panel-reservations': '#2e7d32',
      '--panel-maintenance': '#f9a825',
      '--panel-activity': '#e91e63',
      ...shadow(0.15),
    },
    backgroundImage: '/cats-bg.svg',
    cursor: '/cats-cursor.svg',
  },

  dogs: {
    id: 'dogs',
    name: 'Dogs',
    description: 'Pawsitively adorable 🐕',
    colors: {
      '--bg-dark': '#efebe9',
      '--bg-medium': '#faf7f5',
      '--bg-light': '#fffbf8',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#6d4c41',
      '--primary-light': '#8d6e63',
      '--primary-dark': '#4e342e',
      '--accent1': '#d84315',
      '--accent2': '#0277bd',
      '--accent3': '#558b2f',
      '--status-available': '#2e7d32',
      '--status-checked-out': '#0277bd',
      '--status-reserved': '#ad4e00',
      '--status-needs-attention': '#d84315',
      '--status-missing': '#c62828',
      '--condition-excellent': '#2e7d32',
      '--condition-good': '#558b2f',
      '--condition-fair': '#b86800',
      '--condition-poor': '#ad4e00',
      '--text-primary': '#3e2723',
      '--text-secondary': '#4e342e',
      '--text-muted': '#6d4c41',
      '--border': '#d7ccc8',
      '--border-light': '#efebe9',
      '--danger': '#c62828',
      '--success': '#2e7d32',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#ad4e00',
      '--sidebar-item1': '#6d4c41',
      '--sidebar-item2': '#d84315',
      '--sidebar-item3': '#0277bd',
      '--sidebar-item4': '#558b2f',
      '--sidebar-item5': '#ad4e00',
      '--sidebar-item6': '#7b1fa2',
      '--panel-stats': '#6d4c41',
      '--panel-search': '#0277bd',
      '--panel-checkedout': '#ad4e00',
      '--panel-alerts': '#d84315',
      '--panel-reminders': '#7b1fa2',
      '--panel-lowstock': '#c62828',
      '--panel-reservations': '#558b2f',
      '--panel-maintenance': '#00838f',
      '--panel-activity': '#8d6e63',
      ...shadow(0.15),
    },
    backgroundImage: '/dogs-bg.svg',
    cursor: '/dogs-cursor.svg',
  },

  random: {
    id: 'random',
    name: 'Random',
    description: 'Randomized colors on each switch',
    colors: {},
    isRandom: true,
  },

  custom: {
    id: 'custom',
    name: 'Custom Theme',
    description: 'Create your own color scheme',
    colors: {},
    isCustom: true,
  },
};

// Generate random theme colors
// ============================================================================
// On-color picker — chooses a readable label color (white or near-black)
// for text rendered ON a colored fill (buttons, filled badges). Used by the
// random theme generator and as a fallback for saved custom themes that
// predate the --on-* variables. Handles #hex and hsl()/rgb() strings.
// ============================================================================
export const pickOnColor = (color, mixesTowardBlack = [100]) => {
  const WHITE = [255, 255, 255];
  const BLACK = [11, 13, 16]; // #0b0d10
  const rgb = parseColorToRgb(color);
  if (!rgb) return '#ffffff';
  const contrast = (l1, l2) => (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05);
  // The label must survive on every gradient stop the CSS renders (the .btn
  // gradient mixes the base color toward black at fixed percentages), so
  // evaluate each candidate against its WORST stop.
  const worstFor = (candidate) =>
    Math.min(
      ...mixesTowardBlack.map((pct) => {
        const fill = rgb.map((v) => (v * pct) / 100);
        return contrast(relativeLuminance(candidate), relativeLuminance(fill));
      }),
    );
  return worstFor(WHITE) >= worstFor(BLACK) ? '#ffffff' : '#0b0d10';
};

// Gradient stops used by the .btn / .btn-danger CSS in index.css — keep in
// sync with those rules and with test/theme-contrast.test.js
export const PRIMARY_FILL_MIXES = [88, 62];
export const DANGER_FILL_MIXES = [78, 58];

function parseColorToRgb(c) {
  if (typeof c !== 'string') return null;
  c = c.trim();
  const hex = c.match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i);
  if (hex) {
    let h = hex[1];
    if (h.length === 3) h = h.split('').map((x) => x + x).join('');
    return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16));
  }
  const rgb = c.match(/^rgba?\(([^)]+)\)$/);
  if (rgb) return rgb[1].split(',').slice(0, 3).map((x) => parseFloat(x));
  const hsl = c.match(/^hsla?\(([^)]+)\)$/);
  if (hsl) {
    const [h, s, l] = hsl[1].split(',').map((x) => parseFloat(x));
    return hslToRgb(h, s / 100, l / 100);
  }
  return null;
}

function hslToRgb(h, s, l) {
  h = ((h % 360) + 360) % 360;
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - c / 2;
  const [r, g, b] =
    h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x] :
    h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x];
  return [r + m, g + m, b + m].map((v) => Math.round(v * 255));
}

function relativeLuminance([r, g, b]) {
  const f = (v) => {
    v /= 255;
    return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b);
}

// True when a color reads as a light surface — drives the per-theme
// `color-scheme` (native selects, date pickers, scrollbars). Threshold 0.4
// splits the shipped themes cleanly: light/pastel/xp/etc. above, dark below.
export const isLightColor = (color) => {
  const rgb = parseColorToRgb(color);
  return rgb ? relativeLuminance(rgb) > 0.4 : false;
};

export const generateRandomTheme = () => {
  const randomColor = () =>
    `hsl(${Math.random() * 360}, ${60 + Math.random() * 40}%, ${30 + Math.random() * 40}%)`;
  const randomLight = () =>
    `hsl(${Math.random() * 360}, ${70 + Math.random() * 30}%, ${80 + Math.random() * 15}%)`;
  const randomDark = () =>
    `hsl(${Math.random() * 360}, ${40 + Math.random() * 30}%, ${10 + Math.random() * 15}%)`;

  // On-colors must be computed from the generated fills so button labels
  // stay readable no matter what the dice rolled
  const primary = randomColor();
  const danger = randomColor();
  const success = randomColor();

  return {
    '--bg-dark': randomDark(),
    '--bg-medium': randomDark(),
    '--bg-light': randomDark(),
    '--bg-card': randomDark(),
    '--bg-card-solid': randomDark(),
    '--primary': primary,
    '--primary-light': randomColor(),
    '--primary-dark': randomColor(),
    '--accent1': randomColor(),
    '--accent2': randomColor(),
    '--accent3': randomColor(),
    '--status-available': randomColor(),
    '--status-checked-out': randomColor(),
    '--status-reserved': randomColor(),
    '--status-needs-attention': randomColor(),
    '--status-missing': randomColor(),
    '--condition-excellent': randomColor(),
    '--condition-good': randomColor(),
    '--condition-fair': randomColor(),
    '--condition-poor': randomColor(),
    '--text-primary': randomLight(),
    '--text-secondary': randomLight(),
    '--text-muted': randomColor(),
    '--border': randomColor(),
    '--border-light': randomColor(),
    '--danger': danger,
    '--success': success,
    '--warning': randomColor(),
    '--on-primary': pickOnColor(primary, PRIMARY_FILL_MIXES),
    '--on-danger': pickOnColor(danger, DANGER_FILL_MIXES),
    '--on-success': pickOnColor(success),
    '--sidebar-item1': randomColor(),
    '--sidebar-item2': randomColor(),
    '--sidebar-item3': randomColor(),
    '--sidebar-item4': randomColor(),
    '--sidebar-item5': randomColor(),
    '--sidebar-item6': randomColor(),
    '--panel-stats': randomColor(),
    '--panel-search': randomColor(),
    '--panel-checkedout': randomColor(),
    '--panel-alerts': randomColor(),
    '--panel-reminders': randomColor(),
    '--panel-lowstock': randomColor(),
    '--panel-reservations': randomColor(),
    '--panel-maintenance': randomColor(),
    '--panel-activity': randomColor(),
    '--shadow-sm': `0 1px 2px ${randomDark()}`,
    '--shadow-md': `0 4px 6px ${randomDark()}`,
    '--shadow-lg': `0 10px 15px ${randomDark()}`,
    '--shadow-card': `0 4px 20px ${randomDark()}`,
  };
};
