// ============================================================================
// SIMS Theme Data - All theme definitions in one place
// ============================================================================

// Base color keys that all themes must define
export const COLOR_KEYS = [
  '--bg-dark',
  '--bg-medium',
  '--bg-light',
  '--bg-card',
  '--bg-card-solid',
  '--primary',
  '--primary-light',
  '--primary-dark',
  '--accent1',
  '--accent2',
  '--accent3',
  '--status-available',
  '--status-checked-out',
  '--status-reserved',
  '--status-needs-attention',
  '--status-missing',
  '--condition-excellent',
  '--condition-good',
  '--condition-fair',
  '--condition-poor',
  '--text-primary',
  '--text-secondary',
  '--text-muted',
  '--border',
  '--border-light',
  '--danger',
  '--success',
  '--warning',
  '--on-primary',
  '--on-danger',
  '--on-success',
  '--focus-ring-color',
  '--focus-ring-color-danger',
  '--sidebar-item1',
  '--sidebar-item2',
  '--sidebar-item3',
  '--sidebar-item4',
  '--sidebar-item5',
  '--sidebar-item6',
  '--panel-stats',
  '--panel-search',
  '--panel-checkedout',
  '--panel-alerts',
  '--panel-reminders',
  '--panel-lowstock',
  '--panel-reservations',
  '--panel-maintenance',
  '--panel-activity',
  '--shadow-sm',
  '--shadow-md',
  '--shadow-lg',
  '--shadow-card',
];

// Color categories for the editor UI
export const COLOR_CATEGORIES = {
  backgrounds: {
    label: 'Backgrounds',
    colors: [
      { key: '--bg-dark', label: 'Main Background' },
      { key: '--bg-medium', label: 'Medium Background' },
      { key: '--bg-light', label: 'Light Background' },
      { key: '--bg-card', label: 'Card Background' },
    ],
  },
  primary: {
    label: 'Primary Colors',
    colors: [
      { key: '--primary', label: 'Primary' },
      { key: '--primary-light', label: 'Primary Light' },
      { key: '--primary-dark', label: 'Primary Dark' },
    ],
  },
  accents: {
    label: 'Accent Colors',
    colors: [
      { key: '--accent1', label: 'Accent 1' },
      { key: '--accent2', label: 'Accent 2' },
      { key: '--accent3', label: 'Accent 3' },
    ],
  },
  text: {
    label: 'Text Colors',
    colors: [
      { key: '--text-primary', label: 'Primary Text' },
      { key: '--text-secondary', label: 'Secondary Text' },
      { key: '--text-muted', label: 'Muted Text' },
    ],
  },
  status: {
    label: 'Status Colors',
    colors: [
      { key: '--status-available', label: 'Available' },
      { key: '--status-checked-out', label: 'Checked Out' },
      { key: '--status-reserved', label: 'Reserved' },
      { key: '--status-needs-attention', label: 'Needs Attention' },
      { key: '--status-missing', label: 'Missing' },
    ],
  },
  feedback: {
    label: 'Feedback Colors',
    colors: [
      { key: '--danger', label: 'Danger' },
      { key: '--success', label: 'Success' },
      { key: '--warning', label: 'Warning' },
    ],
  },
  accessibility: {
    label: 'Accessibility',
    colors: [
      { key: '--focus-ring-color', label: 'Focus Ring Color' },
      { key: '--focus-ring-color-danger', label: 'Focus Ring (Danger)' },
    ],
  },
  panels: {
    label: 'Dashboard Panels',
    colors: [
      { key: '--panel-stats', label: 'Statistics' },
      { key: '--panel-search', label: 'Quick Search' },
      { key: '--panel-checkedout', label: 'Checked Out' },
      { key: '--panel-alerts', label: 'Alerts' },
      { key: '--panel-reminders', label: 'Reminders' },
      { key: '--panel-lowstock', label: 'Low Stock' },
      { key: '--panel-reservations', label: 'Reservations' },
      { key: '--panel-maintenance', label: 'Maintenance' },
      { key: '--panel-activity', label: 'Recent Activity' },
    ],
  },
};

// ============================================================================
// Shape + type tokens. Every theme may override any of these via `tokens`;
// ThemeContext always writes the full set (defaults merged under the theme's
// values) so switching themes never leaks a radius or font. Keep the default
// values identical to the :root block in index.css.
// ============================================================================
export const TOKEN_DEFAULTS = {
  '--radius-sm': '4px',
  '--radius-md': '8px',
  '--radius-lg': '10px',
  '--radius-xl': '12px',
  '--radius-2xl': '16px',
  '--font-sans': "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  '--font-heading': 'var(--font-sans)',
  '--font-mono': "ui-monospace, 'SF Mono', 'Cascadia Code', Menlo, Consolas, monospace",
  '--heading-weight': '700',
  '--heading-tracking': '0',
  '--focus-ring-width': '2px',
};

// Theme picker sections, in display order
export const THEME_GROUPS = {
  modern: {
    label: 'Modern',
    description: 'Restrained palettes, readable type and consistent shape — each one varies more than colour.',
  },
  legacy: {
    label: 'Legacy',
    description: 'The original SIMS themes, kept as they were.',
  },
  tools: {
    label: 'Custom & Random',
    description: 'Build your own or roll the dice.',
  },
};

// Shared font stacks (system faces only — the app works offline and never
// loads web fonts)
const FONT_SANS_GEOMETRIC =
  "'Inter', 'SF Pro Text', -apple-system, BlinkMacSystemFont, 'Segoe UI Variable', 'Segoe UI', Roboto, sans-serif";
const FONT_SANS_HUMANIST = "'Avenir Next', 'Avenir', 'Segoe UI', 'Helvetica Neue', system-ui, sans-serif";
const FONT_SANS_ROUNDED =
  "ui-rounded, 'SF Pro Rounded', 'Nunito', 'Varela Round', 'Segoe UI', system-ui, sans-serif";
const FONT_SANS_GROTESK = "'Helvetica Neue', Helvetica, Arial, 'Liberation Sans', system-ui, sans-serif";
const FONT_SERIF_DISPLAY =
  "'Iowan Old Style', 'Palatino Linotype', Palatino, Charter, 'Book Antiqua', Georgia, serif";
const FONT_MONO = "'JetBrains Mono', ui-monospace, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace";

// Default custom theme (used as starting point for custom editor)
export const DEFAULT_CUSTOM_THEME = {
  '--bg-dark': '#1a1d21',
  '--bg-medium': '#22262b',
  '--bg-light': '#2a2f36',
  '--bg-card': '#22262b',
  '--bg-card-solid': '#22262b',
  '--primary': '#5d8aa8',
  '--primary-light': '#7ba3be',
  '--primary-dark': '#4a7089',
  '--accent1': '#6b9e9e',
  '--accent2': '#7a8f7a',
  '--accent3': '#8fa5b5',
  '--status-available': '#6b9e78',
  '--status-checked-out': '#8fa5b5',
  '--status-reserved': '#5d8aa8',
  '--status-needs-attention': '#b58f6b',
  '--status-missing': '#9e6b6b',
  '--condition-excellent': '#6b9e78',
  '--condition-good': '#7a8f7a',
  '--condition-fair': '#b5a56b',
  '--condition-poor': '#b58f6b',
  '--text-primary': '#e2e6ea',
  '--text-secondary': 'rgba(226, 230, 234, 0.65)',
  '--text-muted': 'rgba(226, 230, 234, 0.4)',
  '--border': 'rgba(93, 138, 168, 0.2)',
  '--border-light': 'rgba(93, 138, 168, 0.1)',
  '--danger': '#be7d7d', // brightened from #b56b6b for 4.5:1 error text on --bg-medium
  '--success': '#6b9e78',
  '--on-primary': '#ffffff',
  '--on-danger': '#ffffff',
  '--on-success': '#0b0d10',
  '--warning': '#b5a56b',
  '--focus-ring-color': '#8bb5cc',
  '--focus-ring-color-danger': '#d08080',
  '--sidebar-item1': '#5d8aa8',
  '--sidebar-item2': '#6b9e9e',
  '--sidebar-item3': '#7a8f7a',
  '--sidebar-item4': '#8fa5b5',
  '--sidebar-item5': '#a58f8f',
  '--sidebar-item6': '#9e9e6b',
  '--panel-stats': '#5d8aa8',
  '--panel-search': '#6b9e9e',
  '--panel-checkedout': '#8fa5b5',
  '--panel-alerts': '#b58f6b',
  '--panel-reminders': '#b5a56b',
  '--panel-lowstock': '#9e6b6b',
  '--panel-reservations': '#7a8f7a',
  '--panel-maintenance': '#a58f8f',
  '--panel-activity': '#8f7aa5',
  '--shadow-sm': '0 1px 2px rgba(0, 0, 0, 0.3)',
  '--shadow-md': '0 4px 6px rgba(0, 0, 0, 0.3)',
  '--shadow-lg': '0 10px 15px rgba(0, 0, 0, 0.3)',
  '--shadow-card': '0 4px 20px rgba(0, 0, 0, 0.25)',
};

// Helper to generate shadows
const shadow = (opacity = 0.3) => ({
  '--shadow-sm': `0 1px 2px rgba(0, 0, 0, ${opacity})`,
  '--shadow-md': `0 4px 6px rgba(0, 0, 0, ${opacity})`,
  '--shadow-lg': `0 10px 15px rgba(0, 0, 0, ${opacity})`,
  '--shadow-card': `0 4px 20px rgba(0, 0, 0, ${opacity - 0.05})`,
});

// ============================================================================
// Theme Definitions
// ============================================================================

const LEGACY_THEMES = {
  light: {
    id: 'light',
    group: 'legacy',
    name: 'Light',
    description: 'Clean, standard light theme',
    colors: {
      '--bg-dark': '#f0f2f5',
      '--bg-medium': '#ffffff',
      '--bg-light': '#f8f9fa',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#2563eb',
      '--primary-light': '#3b82f6',
      '--primary-dark': '#1d4ed8',
      '--accent1': '#0891b2',
      '--accent2': '#059669',
      '--accent3': '#7c3aed',
      '--status-available': '#15803d',
      '--status-checked-out': '#2563eb',
      '--status-reserved': '#7c3aed',
      '--status-needs-attention': '#c2410c',
      '--status-missing': '#dc2626',
      '--condition-excellent': '#15803d',
      '--condition-good': '#16a34a',
      '--condition-fair': '#a16207',
      '--condition-poor': '#c2410c',
      '--text-primary': '#1f2937',
      '--text-secondary': '#4b5563',
      '--text-muted': '#636b74',
      '--border': '#e5e7eb',
      '--border-light': '#f3f4f6',
      '--danger': '#dc2626',
      '--success': '#15803d',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#a16207',
      '--sidebar-item1': '#2563eb',
      '--sidebar-item2': '#0891b2',
      '--sidebar-item3': '#059669',
      '--sidebar-item4': '#7c3aed',
      '--sidebar-item5': '#db2777',
      '--sidebar-item6': '#ea580c',
      '--panel-stats': '#2563eb',
      '--panel-search': '#0891b2',
      '--panel-checkedout': '#0d9488',
      '--panel-alerts': '#ea580c',
      '--panel-reminders': '#a16207',
      '--panel-lowstock': '#dc2626',
      '--panel-reservations': '#7c3aed',
      '--panel-maintenance': '#6366f1',
      '--panel-activity': '#059669',
      ...shadow(0.08),
    },
  },

  dark: {
    id: 'dark',
    group: 'legacy',
    name: 'Dark',
    description: 'Default dark theme with muted blue accents',
    colors: { ...DEFAULT_CUSTOM_THEME },
  },

  darker: {
    id: 'darker',
    group: 'legacy',
    name: 'Darker',
    description: 'Pure black backgrounds with grey accents',
    colors: {
      '--bg-dark': '#000000',
      '--bg-medium': '#0a0a0a',
      '--bg-light': '#141414',
      '--bg-card': '#0a0a0a',
      '--bg-card-solid': '#0a0a0a',
      '--primary': '#777777',
      '--primary-light': '#999999',
      '--primary-dark': '#555555',
      '--accent1': '#6e6e6e',
      '--accent2': '#777777',
      '--accent3': '#888888',
      '--status-available': '#6e6e6e',
      '--status-checked-out': '#777777',
      '--status-reserved': '#888888',
      '--status-needs-attention': '#999999',
      '--status-missing': '#aaaaaa',
      '--condition-excellent': '#6e6e6e',
      '--condition-good': '#777777',
      '--condition-fair': '#888888',
      '--condition-poor': '#999999',
      '--text-primary': '#aaaaaa',
      '--text-secondary': '#888888',
      '--text-muted': '#808080',
      '--border': '#333333',
      '--border-light': '#222222',
      '--danger': '#888888',
      '--success': '#6e6e6e',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#999999',
      '--sidebar-item1': '#777777',
      '--sidebar-item2': '#777777',
      '--sidebar-item3': '#777777',
      '--sidebar-item4': '#777777',
      '--sidebar-item5': '#777777',
      '--sidebar-item6': '#777777',
      '--panel-stats': '#555555',
      '--panel-search': '#555555',
      '--panel-checkedout': '#555555',
      '--panel-alerts': '#555555',
      '--panel-reminders': '#555555',
      '--panel-lowstock': '#555555',
      '--panel-reservations': '#555555',
      '--panel-maintenance': '#555555',
      '--panel-activity': '#555555',
      ...shadow(0.5),
    },
  },

  primaries: {
    id: 'primaries',
    group: 'legacy',
    name: 'Primaries',
    description: "Bright primary colors like children's toys",
    colors: {
      '--bg-dark': '#ffeb3b',
      '--bg-medium': '#fff59d',
      '--bg-light': '#fffde7',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#d32f2f',
      '--primary-light': '#e57373',
      '--primary-dark': '#b71c1c',
      '--accent1': '#1565c0',
      '--accent2': '#2e7d32',
      '--accent3': '#e65100',
      '--status-available': '#2e7d32',
      '--status-checked-out': '#1565c0',
      '--status-reserved': '#7b1fa2',
      '--status-needs-attention': '#bf360c',
      '--status-missing': '#c62828',
      '--condition-excellent': '#2e7d32',
      '--condition-good': '#558b2f',
      '--condition-fair': '#b86800',
      '--condition-poor': '#bf360c',
      '--text-primary': '#1a1a1a',
      '--text-secondary': '#333333',
      '--text-muted': '#666666',
      '--border': '#f44336',
      '--border-light': '#ffcdd2',
      '--danger': '#c62828',
      '--success': '#2e7d32',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#e65100',
      '--sidebar-item1': '#d32f2f',
      '--sidebar-item2': '#1565c0',
      '--sidebar-item3': '#2e7d32',
      '--sidebar-item4': '#e65100',
      '--sidebar-item5': '#7b1fa2',
      '--sidebar-item6': '#00838f',
      '--panel-stats': '#1565c0',
      '--panel-search': '#2e7d32',
      '--panel-checkedout': '#00838f',
      '--panel-alerts': '#e65100',
      '--panel-reminders': '#7b1fa2',
      '--panel-lowstock': '#c62828',
      '--panel-reservations': '#d32f2f',
      '--panel-maintenance': '#795548',
      '--panel-activity': '#558b2f',
      '--shadow-sm': '0 2px 4px rgba(244, 67, 54, 0.3)',
      '--shadow-md': '0 4px 8px rgba(33, 150, 243, 0.3)',
      '--shadow-lg': '0 10px 20px rgba(76, 175, 80, 0.3)',
      '--shadow-card': '0 4px 20px rgba(156, 39, 176, 0.25)',
    },
  },

  pastel: {
    id: 'pastel',
    group: 'legacy',
    name: 'Pastel',
    description: 'Soft, pleasing pastel tones',
    colors: {
      '--bg-dark': '#fdf2f8',
      '--bg-medium': '#fefefe',
      '--bg-light': '#f5f3ff',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#7c3aed',
      '--primary-light': '#8b5cf6',
      '--primary-dark': '#6d28d9',
      '--accent1': '#0891b2',
      '--accent2': '#059669',
      '--accent3': '#e11d48',
      '--status-available': '#059669',
      '--status-checked-out': '#2563eb',
      '--status-reserved': '#7c3aed',
      '--status-needs-attention': '#ea580c',
      '--status-missing': '#e11d48',
      '--condition-excellent': '#059669',
      '--condition-good': '#16a34a',
      '--condition-fair': '#8a6914',
      '--condition-poor': '#ea580c',
      '--text-primary': '#374151',
      '--text-secondary': '#4b5563',
      '--text-muted': '#636b74',
      '--border': '#e9d5ff',
      '--border-light': '#f3e8ff',
      '--danger': '#e11d48',
      '--success': '#059669',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#0b0d10',
      '--warning': '#8a6914',
      '--sidebar-item1': '#7c3aed',
      '--sidebar-item2': '#0891b2',
      '--sidebar-item3': '#059669',
      '--sidebar-item4': '#e11d48',
      '--sidebar-item5': '#ea580c',
      '--sidebar-item6': '#4f46e5',
      '--panel-stats': '#7c3aed',
      '--panel-search': '#0891b2',
      '--panel-checkedout': '#059669',
      '--panel-alerts': '#ea580c',
      '--panel-reminders': '#8a6914',
      '--panel-lowstock': '#e11d48',
      '--panel-reservations': '#4f46e5',
      '--panel-maintenance': '#6366f1',
      '--panel-activity': '#0d9488',
      ...shadow(0.1),
    },
  },

  terminal: {
    id: 'terminal',
    group: 'legacy',
    name: 'Terminal',
    description: '80s hacker computer aesthetic',
    colors: {
      '--bg-dark': '#0a0a0a',
      '--bg-medium': '#0d0d0d',
      '--bg-light': '#111111',
      '--bg-card': '#0d0d0d',
      '--bg-card-solid': '#0d0d0d',
      '--primary': '#00ff00',
      '--primary-light': '#33ff33',
      '--primary-dark': '#00cc00',
      '--accent1': '#00ff00',
      '--accent2': '#00dd00',
      '--accent3': '#00bb00',
      '--status-available': '#00ff00',
      '--status-checked-out': '#00cc00',
      '--status-reserved': '#00aa00',
      '--status-needs-attention': '#ffff00',
      '--status-missing': '#ff0000',
      '--condition-excellent': '#00ff00',
      '--condition-good': '#00dd00',
      '--condition-fair': '#ccff00',
      '--condition-poor': '#ffcc00',
      '--text-primary': '#00ff00',
      '--text-secondary': '#00cc00',
      '--text-muted': '#00a600', // brightened from #009900: must stay readable on the panel washes
      '--border': '#00ff00',
      '--border-light': '#004400',
      '--danger': '#ff0000',
      '--success': '#00ff00',
      '--on-primary': '#0b0d10',
      '--on-danger': '#ffffff',
      '--on-success': '#0b0d10',
      '--warning': '#ffff00',
      '--sidebar-item1': '#00ff00',
      '--sidebar-item2': '#00ff66',
      '--sidebar-item3': '#00ffaa',
      '--sidebar-item4': '#66ff00',
      '--sidebar-item5': '#00dd00',
      '--sidebar-item6': '#00cc00',
      /* Panel colors are used as 18–38% alpha washes BEHIND green text —
         they must stay deep and dark or the neon text drowns. Deep CRT-glow
         versions of the original neon hues: */
      '--panel-stats': '#006600',
      '--panel-search': '#006629',
      '--panel-checkedout': '#005e00',
      '--panel-alerts': '#666600',
      '--panel-reminders': '#006644',
      '--panel-lowstock': '#660000',
      '--panel-reservations': '#296600',
      '--panel-maintenance': '#005200',
      '--panel-activity': '#146614',
      '--shadow-sm': '0 0 5px rgba(0, 255, 0, 0.3)',
      '--shadow-md': '0 0 10px rgba(0, 255, 0, 0.3)',
      '--shadow-lg': '0 0 20px rgba(0, 255, 0, 0.3)',
      '--shadow-card': '0 0 15px rgba(0, 255, 0, 0.2)',
    },
    tokens: { '--font-sans': '"Courier New", Courier, monospace' },
  },

  blackwhite: {
    id: 'blackwhite',
    group: 'legacy',
    name: 'Black & White',
    description: 'Pure grayscale aesthetic',
    colors: {
      '--bg-dark': '#ffffff',
      '--bg-medium': '#fafafa',
      '--bg-light': '#f5f5f5',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#333333',
      '--primary-light': '#555555',
      '--primary-dark': '#111111',
      '--accent1': '#444444',
      '--accent2': '#666666',
      '--accent3': '#888888',
      '--status-available': '#333333',
      '--status-checked-out': '#555555',
      '--status-reserved': '#777777',
      '--status-needs-attention': '#757575',
      '--status-missing': '#111111',
      '--condition-excellent': '#222222',
      '--condition-good': '#444444',
      '--condition-fair': '#777777',
      '--condition-poor': '#8d8d8d', // darkened from #999999 for 3:1 on the light card background
      '--text-primary': '#000000',
      '--text-secondary': '#333333',
      '--text-muted': '#6e6e6e',
      '--border': '#cccccc',
      '--border-light': '#eeeeee',
      '--danger': '#000000',
      '--success': '#333333',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#666666',
      '--sidebar-item1': '#333333',
      '--sidebar-item2': '#444444',
      '--sidebar-item3': '#555555',
      '--sidebar-item4': '#666666',
      '--sidebar-item5': '#777777',
      '--sidebar-item6': '#888888',
      '--panel-stats': '#333333',
      '--panel-search': '#555555',
      '--panel-checkedout': '#444444',
      '--panel-alerts': '#777777',
      '--panel-reminders': '#444444',
      '--panel-lowstock': '#222222',
      '--panel-reservations': '#666666',
      '--panel-maintenance': '#555555',
      '--panel-activity': '#333333',
      ...shadow(0.1),
    },
  },

  vibrant: {
    id: 'vibrant',
    group: 'legacy',
    name: 'Vibrant',
    description: 'Bold, saturated complementary colors',
    colors: {
      '--bg-dark': '#1a0a2e',
      '--bg-medium': '#16213e',
      '--bg-light': '#1f3460',
      '--bg-card': '#16213e',
      '--bg-card-solid': '#16213e',
      '--primary': '#ff006e',
      '--primary-light': '#ff4d94',
      '--primary-dark': '#cc0058',
      '--accent1': '#00f5d4',
      '--accent2': '#fee440',
      '--accent3': '#a46aeb',
      '--status-available': '#00f5d4',
      '--status-checked-out': '#00bbf9',
      '--status-reserved': '#a46aeb',
      '--status-needs-attention': '#fee440',
      '--status-missing': '#f15bb5',
      '--condition-excellent': '#00f5d4',
      '--condition-good': '#00bbf9',
      '--condition-fair': '#fee440',
      '--condition-poor': '#f15bb5',
      '--text-primary': '#ffffff',
      '--text-secondary': 'rgba(255, 255, 255, 0.8)',
      '--text-muted': 'rgba(255, 255, 255, 0.5)',
      '--border': 'rgba(255, 0, 110, 0.3)',
      '--border-light': 'rgba(255, 0, 110, 0.15)',
      '--danger': '#f15bb5',
      '--success': '#00f5d4',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#0b0d10',
      '--warning': '#fee440',
      '--sidebar-item1': '#ff006e',
      '--sidebar-item2': '#00f5d4',
      '--sidebar-item3': '#fee440',
      '--sidebar-item4': '#a46aeb',
      '--sidebar-item5': '#00bbf9',
      '--sidebar-item6': '#f15bb5',
      '--panel-stats': '#00f5d4',
      '--panel-search': '#00bbf9',
      '--panel-checkedout': '#a46aeb',
      '--panel-alerts': '#fee440',
      '--panel-reminders': '#00ff87',
      '--panel-lowstock': '#f15bb5',
      '--panel-reservations': '#ff006e',
      '--panel-maintenance': '#00bbf9',
      '--panel-activity': '#fee440',
      '--shadow-sm': '0 1px 3px rgba(255, 0, 110, 0.4)',
      '--shadow-md': '0 4px 8px rgba(0, 245, 212, 0.3)',
      '--shadow-lg': '0 10px 20px rgba(155, 93, 229, 0.3)',
      '--shadow-card': '0 4px 25px rgba(155, 93, 229, 0.4)',
    },
  },

  muted: {
    id: 'muted',
    group: 'legacy',
    name: 'Muted',
    description: 'Soft, desaturated tones',
    colors: {
      '--bg-dark': '#2d2d3a',
      '--bg-medium': '#363646',
      '--bg-light': '#404052',
      '--bg-card': '#363646',
      '--bg-card-solid': '#363646',
      '--primary': '#988088',
      '--primary-light': '#b8a1a8',
      '--primary-dark': '#6e5960',
      '--accent1': '#7ec8b8',
      '--accent2': '#c9b896',
      '--accent3': '#8b7eb8',
      '--status-available': '#7ec8b8',
      '--status-checked-out': '#7eb8c8',
      '--status-reserved': '#9b8ec8',
      '--status-needs-attention': '#c9b896',
      '--status-missing': '#b87e8b',
      '--condition-excellent': '#7ec8b8',
      '--condition-good': '#96c9a8',
      '--condition-fair': '#c9c196',
      '--condition-poor': '#c9a896',
      '--text-primary': '#e8e4e6',
      '--text-secondary': 'rgba(232, 228, 230, 0.7)',
      '--text-muted': 'rgba(232, 228, 230, 0.45)',
      '--border': 'rgba(157, 129, 137, 0.25)',
      '--border-light': 'rgba(157, 129, 137, 0.12)',
      '--danger': '#c595a0', // brightened from #b87e8b for 4.5:1 error text on --bg-medium
      '--danger-fill': '#b87e8b', // filled danger buttons keep the deeper rose (white label needs a dark fill)
      '--success': '#7ec8b8',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#0b0d10',
      '--warning': '#c9b896',
      '--sidebar-item1': '#ad919a',
      '--sidebar-item2': '#7ec8b8',
      '--sidebar-item3': '#c9b896',
      '--sidebar-item4': '#9b8ec8',
      '--sidebar-item5': '#7eb8c8',
      '--sidebar-item6': '#b87e8b',
      '--panel-stats': '#7ec8b8',
      '--panel-search': '#7eb8c8',
      '--panel-checkedout': '#96c9a8',
      '--panel-alerts': '#c9b896',
      '--panel-reminders': '#9b8ec8',
      '--panel-lowstock': '#b87e8b',
      '--panel-reservations': '#ad919a',
      '--panel-maintenance': '#c9a896',
      '--panel-activity': '#8b7eb8',
      ...shadow(0.25),
    },
  },

  xp: {
    id: 'xp',
    group: 'legacy',
    name: 'XP',
    description: 'Windows XP nostalgia',
    colors: {
      '--bg-dark': '#d4cdb8',
      '--bg-medium': '#ece9d8',
      '--bg-light': '#f5f4ea',
      '--bg-card': '#ece9d8',
      '--bg-card-solid': '#ece9d8',
      '--primary': '#003d99',
      '--primary-light': '#1f5faa',
      '--primary-dark': '#002266',
      '--accent1': '#1b7a1b',
      '--accent2': '#9e5000',
      '--accent3': '#990073',
      '--status-available': '#1b7a1b',
      '--status-checked-out': '#003d99',
      '--status-reserved': '#9e5000',
      '--status-needs-attention': '#9e5000',
      '--status-missing': '#a50000',
      '--condition-excellent': '#1b7a1b',
      '--condition-good': '#267326',
      '--condition-fair': '#8a6a00',
      '--condition-poor': '#9e5000',
      '--text-primary': '#222222',
      '--text-secondary': '#444444',
      '--text-muted': '#555555',
      '--border': '#b5ab90',
      '--border-light': '#d4d0c8',
      '--danger': '#a50000',
      '--success': '#1b7a1b',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#9e5000',
      '--sidebar-item1': '#003d99',
      '--sidebar-item2': '#1b7a1b',
      '--sidebar-item3': '#9e5000',
      '--sidebar-item4': '#990073',
      '--sidebar-item5': '#007399',
      '--sidebar-item6': '#7326bf',
      '--panel-stats': '#003d99',
      '--panel-search': '#1b7a1b',
      '--panel-checkedout': '#007399',
      '--panel-alerts': '#9e5000',
      '--panel-reminders': '#990073',
      '--panel-lowstock': '#a50000',
      '--panel-reservations': '#7326bf',
      '--panel-maintenance': '#9e5000',
      '--panel-activity': '#1b7a1b',
      '--shadow-sm': '1px 1px 0 #808080, inset 1px 1px 0 #ffffff',
      '--shadow-md': '2px 2px 0 #808080, inset 1px 1px 0 #ffffff',
      '--shadow-lg': '3px 3px 0 #808080, inset 1px 1px 0 #ffffff',
      '--shadow-card': '2px 2px 5px rgba(0, 0, 0, 0.3)',
    },
  },

  cheese: {
    id: 'cheese',
    group: 'legacy',
    name: 'Cheese',
    description: 'For the cheese enthusiasts 🧀',
    colors: {
      '--bg-dark': '#ffd54f',
      '--bg-medium': '#ffecb3',
      '--bg-light': '#fff8e1',
      '--bg-card': '#fffde7',
      '--bg-card-solid': '#fffde7',
      '--primary': '#bf360c',
      '--primary-light': '#e65100',
      '--primary-dark': '#8c2500',
      '--accent1': '#8d6e63',
      '--accent2': '#a1887f',
      '--accent3': '#bf360c',
      '--status-available': '#8d5600',
      '--status-checked-out': '#bf360c',
      '--status-reserved': '#8c2500',
      '--status-needs-attention': '#b33a00',
      '--status-missing': '#8c0000',
      '--condition-excellent': '#8d5600',
      '--condition-good': '#a06800',
      '--condition-fair': '#b33a00',
      '--condition-poor': '#8c0000',
      '--text-primary': '#4e342e',
      '--text-secondary': '#5d4037',
      '--text-muted': '#795548',
      '--border': '#d4a373',
      '--border-light': '#ffe0b2',
      '--danger': '#8c0000',
      '--success': '#8d5600',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#b33a00',
      '--sidebar-item1': '#bf360c',
      '--sidebar-item2': '#8d6e63',
      '--sidebar-item3': '#a1887f',
      '--sidebar-item4': '#795548',
      '--sidebar-item5': '#6d4c41',
      '--sidebar-item6': '#5d4037',
      '--panel-stats': '#bf360c',
      '--panel-search': '#8d6e63',
      '--panel-checkedout': '#a1887f',
      '--panel-alerts': '#b33a00',
      '--panel-reminders': '#795548',
      '--panel-lowstock': '#8c0000',
      '--panel-reservations': '#6d4c41',
      '--panel-maintenance': '#5d4037',
      '--panel-activity': '#8d5600',
      ...shadow(0.25),
    },
    backgroundImage: '/cheese-bg.svg',
    backgroundOpacity: 0.5,
    cursor: '/cheese-cursor.svg',
  },

  cats: {
    id: 'cats',
    group: 'legacy',
    name: 'Cats',
    description: 'Purrfect for cat lovers 🐱',
    colors: {
      '--bg-dark': '#fce4ec',
      '--bg-medium': '#fff0f5',
      '--bg-light': '#fff5f8',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#c2185b',
      '--primary-light': '#e91e63',
      '--primary-dark': '#880e4f',
      '--accent1': '#7b1fa2',
      '--accent2': '#512da8',
      '--accent3': '#1565c0',
      '--status-available': '#2e7d32',
      '--status-checked-out': '#1565c0',
      '--status-reserved': '#7b1fa2',
      '--status-needs-attention': '#e65100',
      '--status-missing': '#c62828',
      '--condition-excellent': '#2e7d32',
      '--condition-good': '#558b2f',
      '--condition-fair': '#b86800',
      '--condition-poor': '#e65100',
      '--text-primary': '#3e2723',
      '--text-secondary': '#4e342e',
      '--text-muted': '#795548',
      '--border': '#f8bbd9',
      '--border-light': '#fce4ec',
      '--danger': '#c62828',
      '--success': '#2e7d32',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#e65100',
      '--sidebar-item1': '#c2185b',
      '--sidebar-item2': '#7b1fa2',
      '--sidebar-item3': '#512da8',
      '--sidebar-item4': '#1565c0',
      '--sidebar-item5': '#d84315',
      '--sidebar-item6': '#2e7d32',
      '--panel-stats': '#c2185b',
      '--panel-search': '#7b1fa2',
      '--panel-checkedout': '#1565c0',
      '--panel-alerts': '#d84315',
      '--panel-reminders': '#512da8',
      '--panel-lowstock': '#c62828',
      '--panel-reservations': '#2e7d32',
      '--panel-maintenance': '#f9a825',
      '--panel-activity': '#e91e63',
      ...shadow(0.15),
    },
    backgroundImage: '/cats-bg.svg',
    backgroundOpacity: 0.6,
    cursor: '/cats-cursor.svg',
  },

  dogs: {
    id: 'dogs',
    group: 'legacy',
    name: 'Dogs',
    description: 'Pawsitively adorable 🐕',
    colors: {
      '--bg-dark': '#efebe9',
      '--bg-medium': '#faf7f5',
      '--bg-light': '#fffbf8',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#6d4c41',
      '--primary-light': '#8d6e63',
      '--primary-dark': '#4e342e',
      '--accent1': '#d84315',
      '--accent2': '#0277bd',
      '--accent3': '#558b2f',
      '--status-available': '#2e7d32',
      '--status-checked-out': '#0277bd',
      '--status-reserved': '#ad4e00',
      '--status-needs-attention': '#d84315',
      '--status-missing': '#c62828',
      '--condition-excellent': '#2e7d32',
      '--condition-good': '#558b2f',
      '--condition-fair': '#b86800',
      '--condition-poor': '#ad4e00',
      '--text-primary': '#3e2723',
      '--text-secondary': '#4e342e',
      '--text-muted': '#6d4c41',
      '--border': '#d7ccc8',
      '--border-light': '#efebe9',
      '--danger': '#c62828',
      '--success': '#2e7d32',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--warning': '#ad4e00',
      '--sidebar-item1': '#6d4c41',
      '--sidebar-item2': '#d84315',
      '--sidebar-item3': '#0277bd',
      '--sidebar-item4': '#558b2f',
      '--sidebar-item5': '#ad4e00',
      '--sidebar-item6': '#7b1fa2',
      '--panel-stats': '#6d4c41',
      '--panel-search': '#0277bd',
      '--panel-checkedout': '#ad4e00',
      '--panel-alerts': '#d84315',
      '--panel-reminders': '#7b1fa2',
      '--panel-lowstock': '#c62828',
      '--panel-reservations': '#558b2f',
      '--panel-maintenance': '#00838f',
      '--panel-activity': '#8d6e63',
      ...shadow(0.15),
    },
    backgroundImage: '/dogs-bg.svg',
    backgroundOpacity: 0.6,
    cursor: '/dogs-cursor.svg',
  },

  random: {
    id: 'random',
    group: 'tools',
    name: 'Random',
    description: 'Randomized colors on each switch',
    colors: {},
    isRandom: true,
  },

  custom: {
    id: 'custom',
    group: 'tools',
    name: 'Custom Theme',
    description: 'Create your own color scheme',
    colors: {},
    isCustom: true,
  },
};

// ============================================================================
// Modern themes
// Design rules shared by the set: one primary hue per theme (the accents
// support it rather than compete), neutral surfaces that step up in
// lightness from page → sidebar → card, status hues that read as a family,
// body text ≥ 4.5:1 on every surface and status text ≥ 3:1 on cards (see
// test/theme-contrast.test.js). Each theme also sets shape and type tokens
// so the personality comes from more than colour.
// ============================================================================
const MODERN_THEMES = {
  graphite: {
    id: 'graphite',
    group: 'modern',
    name: 'Graphite',
    description: 'Neutral charcoal, one indigo accent, hairline borders',
    colors: {
      '--bg-dark': '#0e1013',
      '--bg-medium': '#15171b',
      '--bg-light': '#1b1e24',
      '--bg-card': '#1b1e24',
      '--bg-card-solid': '#1b1e24',
      '--primary': '#6b6ff0',
      '--primary-light': '#8f93ff',
      '--primary-dark': '#5356c9',
      '--accent1': '#4cc2c9',
      '--accent2': '#c084fc',
      '--accent3': '#f0a35e',
      '--status-available': '#4ade80',
      '--status-checked-out': '#60a5fa',
      '--status-reserved': '#c084fc',
      '--status-needs-attention': '#fbbf24',
      '--status-missing': '#f87171',
      '--condition-excellent': '#4ade80',
      '--condition-good': '#86efac',
      '--condition-fair': '#fbbf24',
      '--condition-poor': '#fb923c',
      '--text-primary': '#e8eaf0',
      '--text-secondary': '#a3a8b5',
      '--text-muted': '#858b99',
      '--border': 'rgba(232, 234, 240, 0.09)',
      '--border-light': 'rgba(232, 234, 240, 0.05)',
      '--danger': '#f87171',
      '--danger-fill': '#dc2626',
      '--success': '#4ade80',
      '--warning': '#fbbf24',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#0b0d10',
      '--sidebar-item1': '#6b6ff0',
      '--sidebar-item2': '#4cc2c9',
      '--sidebar-item3': '#60a5fa',
      '--sidebar-item4': '#c084fc',
      '--sidebar-item5': '#f0a35e',
      '--sidebar-item6': '#4ade80',
      '--panel-stats': '#6b6ff0',
      '--panel-search': '#4cc2c9',
      '--panel-checkedout': '#60a5fa',
      '--panel-alerts': '#f87171',
      '--panel-reminders': '#fbbf24',
      '--panel-lowstock': '#fb923c',
      '--panel-reservations': '#c084fc',
      '--panel-maintenance': '#34d399',
      '--panel-activity': '#a3a8b5',
      '--shadow-sm': '0 1px 2px rgba(0, 0, 0, 0.5)',
      '--shadow-md': '0 4px 10px rgba(0, 0, 0, 0.5)',
      '--shadow-lg': '0 12px 28px rgba(0, 0, 0, 0.6)',
      '--shadow-card': '0 1px 0 rgba(255, 255, 255, 0.03) inset, 0 2px 8px rgba(0, 0, 0, 0.35)',
    },
    tokens: {
      '--radius-sm': '4px',
      '--radius-md': '6px',
      '--radius-lg': '8px',
      '--radius-xl': '10px',
      '--radius-2xl': '14px',
      '--font-sans': FONT_SANS_GEOMETRIC,
      '--heading-weight': '600',
      '--heading-tracking': '-0.01em',
    },
  },

  midnight: {
    id: 'midnight',
    group: 'modern',
    name: 'Midnight',
    description: 'Deep navy with a sky-blue accent and soft glass cards',
    colors: {
      '--bg-dark': '#0a1020',
      '--bg-medium': '#0f172a',
      '--bg-light': '#162138',
      '--bg-card': 'linear-gradient(160deg, rgba(30, 41, 59, 0.85), rgba(22, 33, 56, 0.6))',
      '--bg-card-solid': '#162138',
      '--primary': '#7dd3fc',
      '--primary-light': '#bae6fd',
      '--primary-dark': '#38bdf8',
      '--accent1': '#a78bfa',
      '--accent2': '#34d399',
      '--accent3': '#f472b6',
      '--status-available': '#34d399',
      '--status-checked-out': '#7dd3fc',
      '--status-reserved': '#a78bfa',
      '--status-needs-attention': '#fbbf24',
      '--status-missing': '#fb7185',
      '--condition-excellent': '#34d399',
      '--condition-good': '#86efac',
      '--condition-fair': '#fbbf24',
      '--condition-poor': '#fb923c',
      '--text-primary': '#e6edf7',
      '--text-secondary': '#a9b7cc',
      '--text-muted': '#7f8fa8',
      '--border': 'rgba(125, 211, 252, 0.14)',
      '--border-light': 'rgba(125, 211, 252, 0.08)',
      '--danger': '#fb7185',
      '--danger-fill': '#e11d48',
      '--success': '#34d399',
      '--warning': '#fbbf24',
      '--on-primary': '#0b0d10',
      '--on-danger': '#ffffff',
      '--on-success': '#0b0d10',
      '--sidebar-item1': '#7dd3fc',
      '--sidebar-item2': '#a78bfa',
      '--sidebar-item3': '#34d399',
      '--sidebar-item4': '#f472b6',
      '--sidebar-item5': '#fbbf24',
      '--sidebar-item6': '#fb7185',
      '--panel-stats': '#0ea5e9',
      '--panel-search': '#8b5cf6',
      '--panel-checkedout': '#0284c7',
      '--panel-alerts': '#e11d48',
      '--panel-reminders': '#d97706',
      '--panel-lowstock': '#ea580c',
      '--panel-reservations': '#a78bfa',
      '--panel-maintenance': '#059669',
      '--panel-activity': '#64748b',
      '--shadow-sm': '0 1px 2px rgba(2, 6, 23, 0.6)',
      '--shadow-md': '0 4px 12px rgba(2, 6, 23, 0.6)',
      '--shadow-lg': '0 12px 32px rgba(2, 6, 23, 0.7)',
      '--shadow-card': '0 8px 32px rgba(56, 189, 248, 0.08)',
    },
    tokens: {
      '--radius-sm': '6px',
      '--radius-md': '10px',
      '--radius-lg': '12px',
      '--radius-xl': '14px',
      '--radius-2xl': '18px',
      '--heading-weight': '600',
    },
  },

  arctic: {
    id: 'arctic',
    group: 'modern',
    name: 'Arctic',
    description: 'Cool blue-grey surfaces with frost and aurora accents',
    colors: {
      '--bg-dark': '#242933',
      '--bg-medium': '#2e3440',
      '--bg-light': '#3b4252',
      '--bg-card': '#3b4252',
      '--bg-card-solid': '#3b4252',
      '--primary': '#5a88bf',
      '--primary-light': '#81a1c1',
      '--primary-dark': '#4c7ab0',
      '--accent1': '#88c0d0',
      '--accent2': '#a3be8c',
      '--accent3': '#b48ead',
      '--status-available': '#a3be8c',
      '--status-checked-out': '#88c0d0',
      '--status-reserved': '#b48ead',
      '--status-needs-attention': '#ebcb8b',
      '--status-missing': '#e5868e',
      '--condition-excellent': '#a3be8c',
      '--condition-good': '#8fbcbb',
      '--condition-fair': '#ebcb8b',
      '--condition-poor': '#d08770',
      '--text-primary': '#eceff4',
      '--text-secondary': '#c5cbd6',
      '--text-muted': '#a9b1bf',
      '--border': 'rgba(236, 239, 244, 0.1)',
      '--border-light': 'rgba(236, 239, 244, 0.06)',
      '--danger': '#e5868e',
      '--danger-fill': '#bf616a',
      '--success': '#a3be8c',
      '--warning': '#ebcb8b',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#0b0d10',
      '--sidebar-item1': '#5a88bf',
      '--sidebar-item2': '#88c0d0',
      '--sidebar-item3': '#a3be8c',
      '--sidebar-item4': '#b48ead',
      '--sidebar-item5': '#d08770',
      '--sidebar-item6': '#ebcb8b',
      '--panel-stats': '#81a1c1',
      '--panel-search': '#88c0d0',
      '--panel-checkedout': '#81a1c1',
      '--panel-alerts': '#e5868e',
      '--panel-reminders': '#ebcb8b',
      '--panel-lowstock': '#d08770',
      '--panel-reservations': '#b48ead',
      '--panel-maintenance': '#a3be8c',
      '--panel-activity': '#8fbcbb',
      ...shadow(0.35),
    },
    tokens: {
      '--heading-weight': '600',
    },
  },

  ember: {
    id: 'ember',
    group: 'modern',
    name: 'Ember',
    description: 'Warm charcoal with an amber glow',
    colors: {
      '--bg-dark': '#161311',
      '--bg-medium': '#1e1a17',
      '--bg-light': '#27221e',
      '--bg-card': '#27221e',
      '--bg-card-solid': '#27221e',
      '--primary': '#fbbf24',
      '--primary-light': '#fcd34d',
      '--primary-dark': '#d97706',
      '--accent1': '#fb923c',
      '--accent2': '#f87171',
      '--accent3': '#a3e635',
      '--status-available': '#a3e635',
      '--status-checked-out': '#67e8f9',
      '--status-reserved': '#c4b5fd',
      '--status-needs-attention': '#fb923c',
      '--status-missing': '#f87171',
      '--condition-excellent': '#a3e635',
      '--condition-good': '#bef264',
      '--condition-fair': '#fbbf24',
      '--condition-poor': '#fb923c',
      '--text-primary': '#f3ede6',
      '--text-secondary': '#bfb5a9',
      '--text-muted': '#958c82',
      '--border': 'rgba(251, 191, 36, 0.14)',
      '--border-light': 'rgba(251, 191, 36, 0.07)',
      '--danger': '#f87171',
      '--danger-fill': '#dc2626',
      '--success': '#a3e635',
      '--warning': '#fbbf24',
      '--on-primary': '#0b0d10',
      '--on-danger': '#ffffff',
      '--on-success': '#0b0d10',
      '--sidebar-item1': '#fbbf24',
      '--sidebar-item2': '#fb923c',
      '--sidebar-item3': '#f87171',
      '--sidebar-item4': '#a3e635',
      '--sidebar-item5': '#67e8f9',
      '--sidebar-item6': '#c4b5fd',
      '--panel-stats': '#b45309',
      '--panel-search': '#c2410c',
      '--panel-checkedout': '#22b8cf',
      '--panel-alerts': '#f87171',
      '--panel-reminders': '#a16207',
      '--panel-lowstock': '#fb923c',
      '--panel-reservations': '#a78bfa',
      '--panel-maintenance': '#4d7c0f',
      '--panel-activity': '#78716c',
      ...shadow(0.5),
    },
    tokens: {
      '--radius-sm': '6px',
      '--radius-md': '10px',
      '--radius-lg': '12px',
      '--radius-xl': '14px',
      '--radius-2xl': '18px',
    },
  },

  contrast: {
    id: 'contrast',
    group: 'modern',
    name: 'High Contrast',
    description: 'Black, white and yellow with a heavier focus ring — built for low vision',
    colors: {
      '--bg-dark': '#000000',
      '--bg-medium': '#000000',
      '--bg-light': '#0d0d0d',
      '--bg-card': '#0d0d0d',
      '--bg-card-solid': '#0d0d0d',
      '--primary': '#ffd400',
      '--primary-light': '#ffe14d',
      '--primary-dark': '#e6bf00',
      '--accent1': '#00e5ff',
      '--accent2': '#7cff6b',
      '--accent3': '#ff9af5',
      '--status-available': '#5cff5c',
      '--status-checked-out': '#4dd7ff',
      '--status-reserved': '#d9a6ff',
      '--status-needs-attention': '#ffb347',
      '--status-missing': '#ff6b6b',
      '--condition-excellent': '#5cff5c',
      '--condition-good': '#b5ff7a',
      '--condition-fair': '#ffd400',
      '--condition-poor': '#ffb347',
      '--text-primary': '#ffffff',
      '--text-secondary': '#e6e6e6',
      '--text-muted': '#bdbdbd',
      '--border': '#ffffff',
      '--border-light': '#8a8a8a',
      '--danger': '#ff6b6b',
      '--danger-fill': '#d00000',
      '--success': '#5cff5c',
      '--warning': '#ffb347',
      '--on-primary': '#0b0d10',
      '--on-danger': '#ffffff',
      '--on-success': '#0b0d10',
      '--focus-ring-color': '#ffd400',
      '--focus-ring-color-danger': '#ff6b6b',
      '--sidebar-item1': '#ffd400',
      '--sidebar-item2': '#00e5ff',
      '--sidebar-item3': '#7cff6b',
      '--sidebar-item4': '#ff9af5',
      '--sidebar-item5': '#ffb347',
      '--sidebar-item6': '#4dd7ff',
      /* Panel colours tint the card icon and sub-text as well as the alpha
         wash behind them, so they must stay bright on black */
      '--panel-stats': '#ffd400',
      '--panel-search': '#00e5ff',
      '--panel-checkedout': '#4dd7ff',
      '--panel-alerts': '#ff6b6b',
      '--panel-reminders': '#ffb347',
      '--panel-lowstock': '#ff9af5',
      '--panel-reservations': '#d9a6ff',
      '--panel-maintenance': '#7cff6b',
      '--panel-activity': '#bdbdbd',
      '--shadow-sm': 'none',
      '--shadow-md': 'none',
      '--shadow-lg': 'none',
      '--shadow-card': 'none',
    },
    tokens: {
      '--radius-sm': '2px',
      '--radius-md': '4px',
      '--radius-lg': '4px',
      '--radius-xl': '6px',
      '--radius-2xl': '8px',
      '--focus-ring-width': '3px',
    },
  },

  paper: {
    id: 'paper',
    group: 'modern',
    name: 'Paper',
    description: 'Warm off-white, ink text, terracotta accent and serif headings',
    colors: {
      '--bg-dark': '#f4efe6',
      '--bg-medium': '#fdfbf7',
      '--bg-light': '#fffdf9',
      '--bg-card': '#fffdf9',
      '--bg-card-solid': '#fffdf9',
      '--primary': '#b5452f',
      '--primary-light': '#d35f47',
      '--primary-dark': '#8a3323',
      '--accent1': '#2f6f73',
      '--accent2': '#6b705c',
      '--accent3': '#b08968',
      '--status-available': '#2f7d4f',
      '--status-checked-out': '#2b5f8a',
      '--status-reserved': '#6d4c9a',
      '--status-needs-attention': '#b5651d',
      '--status-missing': '#b3261e',
      '--condition-excellent': '#2f7d4f',
      '--condition-good': '#5a8a3a',
      '--condition-fair': '#9a7b1a',
      '--condition-poor': '#b5651d',
      '--text-primary': '#1f1a17',
      '--text-secondary': '#54493f',
      '--text-muted': '#6f6359',
      '--border': '#e2d9cc',
      '--border-light': '#efe8dd',
      '--danger': '#b3261e',
      '--success': '#2f7d4f',
      '--warning': '#9a6a10',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--sidebar-item1': '#b5452f',
      '--sidebar-item2': '#2f6f73',
      '--sidebar-item3': '#6b705c',
      '--sidebar-item4': '#b08968',
      '--sidebar-item5': '#6d4c9a',
      '--sidebar-item6': '#2f7d4f',
      '--panel-stats': '#b5452f',
      '--panel-search': '#2f6f73',
      '--panel-checkedout': '#2b5f8a',
      '--panel-alerts': '#b3261e',
      '--panel-reminders': '#9a6a10',
      '--panel-lowstock': '#b5651d',
      '--panel-reservations': '#6d4c9a',
      '--panel-maintenance': '#6b705c',
      '--panel-activity': '#b08968',
      '--shadow-sm': 'none',
      '--shadow-md': '0 2px 6px rgba(31, 26, 23, 0.06)',
      '--shadow-lg': '0 8px 24px rgba(31, 26, 23, 0.1)',
      '--shadow-card': 'none',
    },
    tokens: {
      '--radius-sm': '2px',
      '--radius-md': '4px',
      '--radius-lg': '6px',
      '--radius-xl': '8px',
      '--radius-2xl': '10px',
      '--font-sans': FONT_SANS_HUMANIST,
      '--font-heading': FONT_SERIF_DISPLAY,
      '--heading-weight': '600',
      '--heading-tracking': '-0.005em',
    },
  },

  dune: {
    id: 'dune',
    group: 'modern',
    name: 'Dune',
    description: 'Sand and sea-blue in the Solarized tradition, with monospace headings',
    colors: {
      '--bg-dark': '#eee8d5',
      '--bg-medium': '#fdf6e3',
      '--bg-light': '#fffbf0',
      '--bg-card': '#fffbf0',
      '--bg-card-solid': '#fffbf0',
      '--primary': '#268bd2',
      '--primary-light': '#4aa3e0',
      '--primary-dark': '#1e6fa8',
      '--accent1': '#2aa198',
      '--accent2': '#859900',
      '--accent3': '#6c71c4',
      '--status-available': '#859900',
      '--status-checked-out': '#268bd2',
      '--status-reserved': '#6c71c4',
      '--status-needs-attention': '#cb4b16',
      '--status-missing': '#c9302c',
      '--condition-excellent': '#859900',
      '--condition-good': '#2aa198',
      '--condition-fair': '#b58900',
      '--condition-poor': '#cb4b16',
      '--text-primary': '#073642',
      '--text-secondary': '#586e75',
      '--text-muted': '#5c7177',
      '--border': '#d9d2bd',
      '--border-light': '#e8e2cf',
      '--danger': '#c9302c',
      '--success': '#859900',
      '--warning': '#b58900',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#0b0d10',
      '--sidebar-item1': '#268bd2',
      '--sidebar-item2': '#2aa198',
      '--sidebar-item3': '#859900',
      '--sidebar-item4': '#6c71c4',
      '--sidebar-item5': '#d33682',
      '--sidebar-item6': '#cb4b16',
      '--panel-stats': '#268bd2',
      '--panel-search': '#2aa198',
      '--panel-checkedout': '#6c71c4',
      '--panel-alerts': '#cb4b16',
      '--panel-reminders': '#b58900',
      '--panel-lowstock': '#dc322f',
      '--panel-reservations': '#859900',
      '--panel-maintenance': '#d33682',
      '--panel-activity': '#657b83',
      ...shadow(0.06),
    },
    tokens: {
      '--radius-sm': '3px',
      '--radius-md': '5px',
      '--radius-lg': '6px',
      '--radius-xl': '8px',
      '--radius-2xl': '10px',
      '--font-heading': FONT_MONO,
      '--heading-weight': '600',
      '--heading-tracking': '-0.02em',
    },
  },

  sage: {
    id: 'sage',
    group: 'modern',
    name: 'Sage',
    description: 'Soft greens, generous corners and a rounded face',
    colors: {
      '--bg-dark': '#eef3ee',
      '--bg-medium': '#f8faf7',
      '--bg-light': '#ffffff',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#3a7d5c',
      '--primary-light': '#4f9a75',
      '--primary-dark': '#2c6147',
      '--accent1': '#5b8bd6',
      '--accent2': '#c9883a',
      '--accent3': '#8a6cc1',
      '--status-available': '#2e8b57',
      '--status-checked-out': '#2f6fbf',
      '--status-reserved': '#7a57c2',
      '--status-needs-attention': '#c2710f',
      '--status-missing': '#c7372f',
      '--condition-excellent': '#2e8b57',
      '--condition-good': '#5a9e3a',
      '--condition-fair': '#b07a14',
      '--condition-poor': '#c2710f',
      '--text-primary': '#1e2a23',
      '--text-secondary': '#4a5a50',
      '--text-muted': '#627268',
      '--border': '#d6e0d8',
      '--border-light': '#e6ede7',
      '--danger': '#c7372f',
      '--success': '#27774a',
      '--warning': '#b07a14',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--sidebar-item1': '#3a7d5c',
      '--sidebar-item2': '#5b8bd6',
      '--sidebar-item3': '#c9883a',
      '--sidebar-item4': '#8a6cc1',
      '--sidebar-item5': '#2f6fbf',
      '--sidebar-item6': '#c7372f',
      '--panel-stats': '#3a7d5c',
      '--panel-search': '#5b8bd6',
      '--panel-checkedout': '#2f6fbf',
      '--panel-alerts': '#c7372f',
      '--panel-reminders': '#b5702a',
      '--panel-lowstock': '#c2710f',
      '--panel-reservations': '#8a6cc1',
      '--panel-maintenance': '#5a9e3a',
      '--panel-activity': '#627268',
      ...shadow(0.06),
    },
    tokens: {
      '--radius-sm': '8px',
      '--radius-md': '12px',
      '--radius-lg': '14px',
      '--radius-xl': '16px',
      '--radius-2xl': '20px',
      '--font-sans': FONT_SANS_ROUNDED,
    },
  },

  studio: {
    id: 'studio',
    group: 'modern',
    name: 'Studio',
    description: 'Black on white, square corners, hard shadows and one electric blue',
    colors: {
      '--bg-dark': '#f5f5f5',
      '--bg-medium': '#ffffff',
      '--bg-light': '#ffffff',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#0038ff',
      '--primary-light': '#3d66ff',
      '--primary-dark': '#0029b8',
      '--accent1': '#111111',
      '--accent2': '#555555',
      '--accent3': '#0038ff',
      '--status-available': '#0f7a3a',
      '--status-checked-out': '#0038ff',
      '--status-reserved': '#6b21a8',
      '--status-needs-attention': '#b45309',
      '--status-missing': '#c81e1e',
      '--condition-excellent': '#0f7a3a',
      '--condition-good': '#3b7a16',
      '--condition-fair': '#a16207',
      '--condition-poor': '#b45309',
      '--text-primary': '#111111',
      '--text-secondary': '#3d3d3d',
      '--text-muted': '#5c5c5c',
      '--border': '#111111',
      '--border-light': '#e5e5e5',
      '--danger': '#c81e1e',
      '--success': '#0f7a3a',
      '--warning': '#a16207',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--sidebar-item1': '#111111',
      '--sidebar-item2': '#111111',
      '--sidebar-item3': '#111111',
      '--sidebar-item4': '#111111',
      '--sidebar-item5': '#111111',
      '--sidebar-item6': '#111111',
      '--panel-stats': '#0038ff',
      '--panel-search': '#111111',
      '--panel-checkedout': '#0038ff',
      '--panel-alerts': '#c81e1e',
      '--panel-reminders': '#a16207',
      '--panel-lowstock': '#b45309',
      '--panel-reservations': '#6b21a8',
      '--panel-maintenance': '#111111',
      '--panel-activity': '#555555',
      '--shadow-sm': 'none',
      '--shadow-md': '2px 2px 0 #111111',
      '--shadow-lg': '6px 6px 0 #111111',
      '--shadow-card': '4px 4px 0 #111111',
    },
    tokens: {
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--radius-xl': '0px',
      '--radius-2xl': '0px',
      '--font-sans': FONT_SANS_GROTESK,
      '--heading-weight': '800',
      '--heading-tracking': '-0.02em',
    },
  },

  slate: {
    id: 'slate',
    group: 'modern',
    name: 'Slate',
    description: 'Crisp blue-grey with an indigo accent over a faint dot grid',
    colors: {
      '--bg-dark': '#f1f5f9',
      '--bg-medium': '#ffffff',
      '--bg-light': '#ffffff',
      '--bg-card': '#ffffff',
      '--bg-card-solid': '#ffffff',
      '--primary': '#4f46e5',
      '--primary-light': '#6366f1',
      '--primary-dark': '#4338ca',
      '--accent1': '#0891b2',
      '--accent2': '#059669',
      '--accent3': '#db2777',
      '--status-available': '#047857',
      '--status-checked-out': '#2563eb',
      '--status-reserved': '#7c3aed',
      '--status-needs-attention': '#c2410c',
      '--status-missing': '#dc2626',
      '--condition-excellent': '#047857',
      '--condition-good': '#16a34a',
      '--condition-fair': '#a16207',
      '--condition-poor': '#c2410c',
      '--text-primary': '#0f172a',
      '--text-secondary': '#475569',
      '--text-muted': '#64748b',
      '--border': '#e2e8f0',
      '--border-light': '#f1f5f9',
      '--danger': '#dc2626',
      '--success': '#047857',
      '--warning': '#a16207',
      '--on-primary': '#ffffff',
      '--on-danger': '#ffffff',
      '--on-success': '#ffffff',
      '--sidebar-item1': '#4f46e5',
      '--sidebar-item2': '#0891b2',
      '--sidebar-item3': '#059669',
      '--sidebar-item4': '#db2777',
      '--sidebar-item5': '#ea580c',
      '--sidebar-item6': '#7c3aed',
      '--panel-stats': '#4f46e5',
      '--panel-search': '#0891b2',
      '--panel-checkedout': '#2563eb',
      '--panel-alerts': '#ea580c',
      '--panel-reminders': '#a16207',
      '--panel-lowstock': '#dc2626',
      '--panel-reservations': '#7c3aed',
      '--panel-maintenance': '#059669',
      '--panel-activity': '#64748b',
      '--shadow-sm': '0 1px 2px rgba(15, 23, 42, 0.06)',
      '--shadow-md': '0 4px 8px rgba(15, 23, 42, 0.08)',
      '--shadow-lg': '0 12px 24px rgba(15, 23, 42, 0.12)',
      '--shadow-card': '0 1px 3px rgba(15, 23, 42, 0.08)',
    },
    backgroundImage: '/textures/dots.svg',
    tokens: {
      '--radius-sm': '6px',
      '--radius-md': '8px',
      '--radius-lg': '10px',
      '--radius-xl': '12px',
      '--radius-2xl': '16px',
      '--font-sans': FONT_SANS_GEOMETRIC,
      '--heading-weight': '600',
      '--heading-tracking': '-0.01em',
    },
  },
};

// Modern first so the picker (Object.values order) leads with them; the
// default theme stays `dark` (ThemeContext) until the user picks another
export const themes = { ...MODERN_THEMES, ...LEGACY_THEMES };

// Ids of the themes that shipped before the Modern set — the picker's
// Legacy section. Exported so tests can assert the grouping stays stable.
export const LEGACY_THEME_IDS = Object.keys(LEGACY_THEMES).filter(
  (id) => LEGACY_THEMES[id].group === 'legacy',
);
export const MODERN_THEME_IDS = Object.keys(MODERN_THEMES);

// Generate random theme colors
// ============================================================================
// On-color picker — chooses a readable label color (white or near-black)
// for text rendered ON a colored fill (buttons, filled badges). Used by the
// random theme generator and as a fallback for saved custom themes that
// predate the --on-* variables. Handles #hex and hsl()/rgb() strings.
// ============================================================================
export const pickOnColor = (color, mixesTowardBlack = [100]) => {
  const WHITE = [255, 255, 255];
  const BLACK = [11, 13, 16]; // #0b0d10
  const rgb = parseColorToRgb(color);
  if (!rgb) return '#ffffff';
  const contrast = (l1, l2) => (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05);
  // The label must survive on every gradient stop the CSS renders (the .btn
  // gradient mixes the base color toward black at fixed percentages), so
  // evaluate each candidate against its WORST stop.
  const worstFor = (candidate) =>
    Math.min(
      ...mixesTowardBlack.map((pct) => {
        const fill = rgb.map((v) => (v * pct) / 100);
        return contrast(relativeLuminance(candidate), relativeLuminance(fill));
      }),
    );
  return worstFor(WHITE) >= worstFor(BLACK) ? '#ffffff' : '#0b0d10';
};

// Gradient stops used by the .btn / .btn-danger CSS in index.css — keep in
// sync with those rules and with test/theme-contrast.test.js
export const PRIMARY_FILL_MIXES = [88, 62];
export const DANGER_FILL_MIXES = [78, 58];

function parseColorToRgb(c) {
  if (typeof c !== 'string') return null;
  c = c.trim();
  const hex = c.match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i);
  if (hex) {
    let h = hex[1];
    if (h.length === 3) h = h.split('').map((x) => x + x).join('');
    return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16));
  }
  const rgb = c.match(/^rgba?\(([^)]+)\)$/);
  if (rgb) return rgb[1].split(',').slice(0, 3).map((x) => parseFloat(x));
  const hsl = c.match(/^hsla?\(([^)]+)\)$/);
  if (hsl) {
    const [h, s, l] = hsl[1].split(',').map((x) => parseFloat(x));
    return hslToRgb(h, s / 100, l / 100);
  }
  return null;
}

function hslToRgb(h, s, l) {
  h = ((h % 360) + 360) % 360;
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - c / 2;
  const [r, g, b] =
    h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x] :
    h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x];
  return [r + m, g + m, b + m].map((v) => Math.round(v * 255));
}

function relativeLuminance([r, g, b]) {
  const f = (v) => {
    v /= 255;
    return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b);
}

// True when a color reads as a light surface — drives the per-theme
// `color-scheme` (native selects, date pickers, scrollbars). Threshold 0.4
// splits the shipped themes cleanly: light/pastel/xp/etc. above, dark below.
export const isLightColor = (color) => {
  const rgb = parseColorToRgb(color);
  return rgb ? relativeLuminance(rgb) > 0.4 : false;
};

export const generateRandomTheme = () => {
  const randomColor = () =>
    `hsl(${Math.random() * 360}, ${60 + Math.random() * 40}%, ${30 + Math.random() * 40}%)`;
  const randomLight = () =>
    `hsl(${Math.random() * 360}, ${70 + Math.random() * 30}%, ${80 + Math.random() * 15}%)`;
  const randomDark = () =>
    `hsl(${Math.random() * 360}, ${40 + Math.random() * 30}%, ${10 + Math.random() * 15}%)`;

  // On-colors must be computed from the generated fills so button labels
  // stay readable no matter what the dice rolled
  const primary = randomColor();
  const danger = randomColor();
  const success = randomColor();

  return {
    '--bg-dark': randomDark(),
    '--bg-medium': randomDark(),
    '--bg-light': randomDark(),
    '--bg-card': randomDark(),
    '--bg-card-solid': randomDark(),
    '--primary': primary,
    '--primary-light': randomColor(),
    '--primary-dark': randomColor(),
    '--accent1': randomColor(),
    '--accent2': randomColor(),
    '--accent3': randomColor(),
    '--status-available': randomColor(),
    '--status-checked-out': randomColor(),
    '--status-reserved': randomColor(),
    '--status-needs-attention': randomColor(),
    '--status-missing': randomColor(),
    '--condition-excellent': randomColor(),
    '--condition-good': randomColor(),
    '--condition-fair': randomColor(),
    '--condition-poor': randomColor(),
    '--text-primary': randomLight(),
    '--text-secondary': randomLight(),
    '--text-muted': randomColor(),
    '--border': randomColor(),
    '--border-light': randomColor(),
    '--danger': danger,
    '--success': success,
    '--warning': randomColor(),
    '--on-primary': pickOnColor(primary, PRIMARY_FILL_MIXES),
    '--on-danger': pickOnColor(danger, DANGER_FILL_MIXES),
    '--on-success': pickOnColor(success),
    '--sidebar-item1': randomColor(),
    '--sidebar-item2': randomColor(),
    '--sidebar-item3': randomColor(),
    '--sidebar-item4': randomColor(),
    '--sidebar-item5': randomColor(),
    '--sidebar-item6': randomColor(),
    '--panel-stats': randomColor(),
    '--panel-search': randomColor(),
    '--panel-checkedout': randomColor(),
    '--panel-alerts': randomColor(),
    '--panel-reminders': randomColor(),
    '--panel-lowstock': randomColor(),
    '--panel-reservations': randomColor(),
    '--panel-maintenance': randomColor(),
    '--panel-activity': randomColor(),
    '--shadow-sm': `0 1px 2px ${randomDark()}`,
    '--shadow-md': `0 4px 6px ${randomDark()}`,
    '--shadow-lg': `0 10px 15px ${randomDark()}`,
    '--shadow-card': `0 4px 20px ${randomDark()}`,
  };
};
