// ============================================================================
// Smart Paste Constants
// Centralized data constants used across parser modules
// ============================================================================

// Known brand names for detection
export const KNOWN_BRANDS = [
  'Sony',
  'Canon',
  'Nikon',
  'Panasonic',
  'Blackmagic',
  'RED',
  'ARRI',
  'Fujifilm',
  'Fuji',
  'Leica',
  'Zeiss',
  'Sigma',
  'Tamron',
  'Tokina',
  'Rokinon',
  'Samyang',
  'Voigtlander',
  'Sennheiser',
  'Rode',
  'Røde',
  'Shure',
  'Audio-Technica',
  'Zoom',
  'Tascam',
  'Sound Devices',
  'Aputure',
  'Godox',
  'Profoto',
  'Broncolor',
  'Litepanels',
  'Kino Flo',
  'Nanlite',
  'Astera',
  'DJI',
  'Zhiyun',
  'Manfrotto',
  'Gitzo',
  'Sachtler',
  'Tilta',
  'SmallRig',
  'Wooden Camera',
  'Atomos',
  'SmallHD',
  'Teradek',
  'Hollyland',
  'SanDisk',
  'Samsung',
  'Lexar',
  'ProGrade',
  'Apple',
  'Blackmagic Design',
  'Davinci',
  'Avid',
  'Neewer',
  'Elgato',
  'K-Tek',
  'Rycote',
  'Bubblebee',
  'Lectrosonics',
  'Wisycom',
  'Zaxcom',
  'Cooke',
  'Angenieux',
  'Fujinon',
  'Schneider',
  'Tiffen',
  'Lee Filters',
  'NiSi',
  'Matthews',
  'Avenger',
  'Kupo',
  'American Grip',
  'Modern Studio',
  'OConnor',
  'Vinten',
  'Miller',
  'Cartoni',
  'Libec',
  'Benro',
  'Peak Design',
  'Sanken',
  'DPA',
  'Schoeps',
  'Neumann',
  'AKG',
  'Beyerdynamic',
  'Anton Bauer',
  'IDX',
  'Core SWX',
  'Hawk-Woods',
  'Bebob',
  'Dedolight',
  'Mole-Richardson',
  'Quasar Science',
  'Pelican',
  'SKB',
  'Nanuk',
  'Porta Brace',
  'Tenba',
  'Think Tank',
  'Deity',
  'Tentacle Sync',
  'Timecode Systems',
];

// Category keywords mapping
export const CATEGORY_KEYWORDS = {
  Cameras: [
    'camera',
    'camcorder',
    'cinema camera',
    'mirrorless',
    'dslr',
    'sensor type',
    'video camera',
    'digital camera',
  ],
  Lenses: [
    'lens',
    'focal length',
    'aperture',
    'f/',
    'prime lens',
    'zoom lens',
    'wide angle',
    'telephoto',
    'anamorphic',
  ],
  Lighting: [
    'light',
    'led',
    'strobe',
    'flash',
    'softbox',
    'panel',
    'fresnel',
    'rgb light',
    'bi-color',
    'watt',
    'lumen',
    'fixture',
  ],
  Audio: [
    'microphone',
    'mic',
    'audio',
    'recorder',
    'wireless system',
    'lavalier',
    'shotgun',
    'boom pole',
    'preamp',
    'mixer',
  ],
  Support: [
    'tripod',
    'monopod',
    'gimbal',
    'stabilizer',
    'fluid head',
    'slider',
    'dolly',
    'jib',
    'crane',
    'rig',
  ],
  Grip: [
    'c-stand',
    'grip head',
    'arm',
    'clamp',
    'flag',
    'frame',
    'silk',
    'net',
    'scrim',
    'gobo',
    'sandbag',
  ],
  Accessories: [
    'battery',
    'charger',
    'cable',
    'adapter',
    'mount',
    'cage',
    'filter',
    'hood',
    'follow focus',
  ],
  Storage: ['card', 'ssd', 'drive', 'memory card', 'cfast', 'sd card', 'storage', 'cfexpress'],
  Monitors: [
    'monitor',
    'display',
    'screen',
    'viewfinder',
    'evf',
    'on-camera monitor',
    'field monitor',
  ],
  Power: ['v-mount', 'gold mount', 'power supply', 'battery plate', 'ac adapter', 'battery pack'],
  Consumables: ['tape', 'gel', 'diffusion', 'gaffer', 'expendable'],
};

// Abbreviation expansions for fuzzy matching
export const ABBREVIATIONS = {
  freq: 'frequency',
  temp: 'temperature',
  max: 'maximum',
  min: 'minimum',
  mic: 'microphone',
  res: 'resolution',
  conn: 'connector',
  dim: 'dimensions',
  wt: 'weight',
  bat: 'battery',
  batt: 'battery',
  vol: 'voltage',
  pwr: 'power',
  cap: 'capacity',
  compat: 'compatibility',
  stab: 'stabilization',
  adj: 'adjustment',
  diam: 'diameter',
  ht: 'height',
  len: 'length',
  sens: 'sensitivity',
  imp: 'impedance',
  approx: 'approximate',
  incl: 'included',
  info: 'information',
  spec: 'specification',
  specs: 'specifications',
  num: 'number',
  qty: 'quantity',
  ext: 'extended',
  dia: 'diameter',
  opt: 'optical',
  mech: 'mechanical',
  elec: 'electronic',
  def: 'definition',
  vid: 'video',
  aud: 'audio',
  rec: 'recording',
  cont: 'continuous',
  std: 'standard',
};

// Stop words filtered during token-level matching
export const STOP_WORDS = new Set([
  'type',
  'size',
  'rate',
  'range',
  'mode',
  'with',
  'from',
  'for',
  'the',
  'and',
  'max',
  'min',
  'output',
  'input',
  'total',
  'number',
  'system',
  'included',
  'support',
  'supported',
  'compatible',
  'maximum',
  'minimum',
  'speed',
  'level',
  'control',
  'depth',
  'life',
  'time',
  'capacity',
  'power',
  'count',
  'body',
  'recording',
  'card',
  'cable',
  'mount',
  'class',
  'general',
  'specification',
  'specifications',
  'key',
  'features',
  'feature',
  'details',
  'detail',
  'info',
  'information',
  'other',
  'additional',
  'about',
  'product',
  'item',
]);

// Common spec name aliases for matching
export const COMMON_ALIASES = {
  'sensor type': ['sensor', 'image sensor', 'sensor specification'],
  'sensor size': ['format', 'image circle', 'coverage', 'sensor format'],
  'effective pixels': [
    'megapixels',
    'mp',
    'resolution',
    'pixel count',
    'total pixels',
    'image resolution',
  ],
  'video resolution': [
    'video',
    'video recording',
    'movie recording',
    'max video',
    '4k',
    '8k',
    'video capability',
    'recording resolution',
  ],
  'frame rates': ['frame rate', 'fps', 'recording fps'],
  'mount type': ['modifier mount', 'accessory mount', 'bowens mount', 'battery mount'],
  'lens mount': ['mount', 'camera mount', 'mount type', 'bayonet mount'],
  'focal length': ['zoom range', 'focal range', 'fl'],
  'maximum aperture': [
    'max aperture',
    'aperture',
    'f-stop',
    'fastest aperture',
    'widest aperture',
    'speed',
    'wide open',
  ],
  'minimum aperture': ['min aperture', 'smallest aperture'],
  'light type': ['lamp type', 'bulb type', 'light source', 'emitter type'],
  'power output': [
    'max power output',
    'output power',
    'wattage',
    'watts',
    'max power',
    'power',
    'equivalent wattage',
  ],
  'color temperature': ['color temp', 'cct', 'cct range', 'kelvin', 'white balance'],
  'cct range': ['color temperature range', 'temp range', 'kelvin range'],
  'microphone type': ['mic type', 'transducer', 'capsule type'],
  'transducer type': ['capsule', 'element type'],
  'polar pattern': ['pickup pattern', 'pattern', 'directivity', 'directionality'],
  'frequency response': ['freq response', 'frequency range', 'bandwidth'],
  'output connector': ['connector', 'connection', 'connector type', 'output type'],
  'max payload': ['payload', 'payload capacity', 'max load', 'load capacity', 'maximum payload'],
  capacity: [
    'storage capacity',
    'total capacity',
    'storage size',
    'watt hours',
    'wh',
    'mah',
    'milliamp hours',
  ],
  compatibility: ['compatible with', 'works with', 'supported devices'],
  weight: ['body weight', 'total weight', 'net weight', 'unit weight', 'approx weight'],
  dimensions: [
    'size',
    'body size',
    'measurements',
    'lxwxh',
    'exterior dimensions',
    'overall dimensions',
    'wxhxd',
  ],
  'iso range': [
    'iso',
    'iso sensitivity',
    'iso speed',
    'native iso',
    'native iso range',
    'extended iso',
    'extended iso range',
    'dual native iso',
  ],
  'af system': ['autofocus', 'autofocus system', 'focus system', 'af type'],
  'af points': ['focus points', 'autofocus points', 'af coverage'],
  stabilization: ['image stabilization', 'ibis', 'ois', 'vr', 'is', 'steady shot', 'sensor shift'],
  'wireless connectivity': ['wifi', 'wi-fi', 'bluetooth', 'wireless', 'nfc'],
  'battery life': ['shots per charge', 'battery duration', 'runtime'],
  'battery type': ['battery', 'power source', 'battery model'],
  'weather sealing': [
    'weather sealed',
    'dust proof',
    'moisture resistant',
    'environmental sealing',
    'splash proof',
  ],
  'screen size': ['display size', 'lcd size', 'monitor size'],
  'panel type': ['display type', 'lcd type', 'screen type'],
  brightness: ['luminance', 'nits', 'cd/m2', 'max brightness'],
  'read speed': ['max read', 'sequential read', 'read rate'],
  'write speed': ['max write', 'sequential write', 'write rate'],
  'image stabilization': [
    'stabilization',
    'ois',
    'lens stabilization',
    'vr',
    'is',
    'optical stabilization',
  ],
  'filter thread': ['filter size', 'front filter', 'front thread'],
  'self-noise': ['self noise', 'equivalent noise', 'noise level', 'noise floor'],
  sensitivity: ['mic sensitivity', 'output level'],
  'max spl': ['maximum spl', 'max sound pressure', 'clipping level'],
  cri: ['color rendering', 'color rendering index', 'ra'],
  tlci: ['television lighting consistency', 'television lighting consistency index'],
  'beam angle': ['beam spread', 'coverage angle', 'field angle'],
  'power draw': ['power consumption', 'wattage', 'max draw', 'current draw'],
  voltage: ['nominal voltage', 'output voltage', 'operating voltage'],
  'charge time': ['charging time', 'recharge time', 'full charge'],
  'head type': ['fluid head', 'head style', 'pan tilt head'],
  'max height': ['maximum height', 'extended height', 'full height'],
  'leg sections': ['sections', 'number of sections'],
  'support type': ['tripod type', 'stand type'],
  'min height': ['minimum height', 'lowest height'],
  'continuous shooting': ['burst rate', 'drive speed', 'continuous drive'],
  'shutter speed range': ['shutter speed', 'shutter range', 'mechanical shutter'],
  'lcd screen': ['lcd', 'rear display', 'rear screen'],
  'viewfinder type': ['evf', 'viewfinder', 'ovf', 'electronic viewfinder'],
  'memory card slots': ['card slots', 'media slots', 'memory slots'],
  'card types supported': ['supported cards', 'media type', 'compatible cards', 'card type'],
  'video output': ['hdmi output', 'video out', 'hdmi', 'sdi'],
  'audio input': ['mic input', 'audio in', 'microphone input', 'xlr input'],
  'optical design': ['lens construction', 'elements/groups', 'optical formula', 'lens design'],
  'diaphragm blades': ['aperture blades', 'iris blades', 'number of blades'],
  'minimum focus distance': [
    'mfd',
    'close focus',
    'closest focus',
    'near limit',
    'closest focusing distance',
  ],
  'maximum magnification': ['max magnification', 'magnification ratio', 'reproduction ratio'],
  autofocus: ['af', 'auto focus', 'focus motor'],
  'luminous flux (lm)': ['lumens', 'lumen output', 'lm', 'total output'],
  'illuminance (lux)': ['lux', 'lux output', 'lux at 1m'],
  'modifier mount': ['bowens mount', 'light modifier', 'accessory mount'],
  'wireless control': ['app control', 'remote control', 'bluetooth control'],
  'signal-to-noise ratio': ['snr', 's/n ratio', 'signal to noise'],
  'dynamic range': ['dr'],
  'phantom power': ['48v', 'phantom', 'p48', 'plug-in power'],
  'wireless frequency': ['frequency band', 'rf frequency', 'wireless band'],
  'wireless range': ['operating range', 'transmission range', 'rf range', 'line of sight range'],
  'capacity (wh)': ['watt hours', 'wh', 'energy capacity'],
  'capacity (mah)': ['mah', 'milliamp hours', 'amp hours'],
  'angle of view': ['aov', 'field of view', 'fov'],
  'af motor type': ['focus motor', 'af drive', 'af motor'],
  'lens format coverage': ['coverage', 'image circle', 'format coverage', 'sensor coverage'],
  'video format': ['codec', 'recording format', 'compression', 'video codec'],
  'bit depth': ['color depth', 'color bit depth'],
  'chroma subsampling': ['chroma', 'color subsampling', 'subsampling'],
  'hdr recording': ['hdr', 'hdr video', 'hlg', 'high dynamic range'],
  'af detection': ['af subject detection', 'subject tracking', 'eye af', 'face detection'],
  'viewfinder coverage': ['evf coverage', 'viewfinder magnification'],
  'body material': ['construction', 'chassis', 'body construction', 'housing'],
  'image processor': ['processor', 'engine', 'image engine', 'processing engine'],
  'cooling system': ['fan', 'cooling', 'active cooling', 'heat dissipation'],
  'storage type': ['media type', 'drive type', 'interface type'],
  interface: ['connection type', 'bus type'],
  'form factor': ['card size', 'physical size'],
  'video speed class': ['v class', 'video class'],
  'aspect ratio': ['display ratio', 'screen ratio'],
  'contrast ratio': ['contrast', 'static contrast'],
  'color gamut': ['gamut', 'color space', 'rec 709', 'dci p3'],
  touchscreen: ['touch', 'touch input', 'touch display'],
  'focus assist': ['peaking', 'focus peaking', 'punch in'],
  chemistry: ['cell chemistry', 'cell type', 'battery chemistry'],
  'max discharge': ['continuous draw', 'max current', 'peak current'],
  'protection circuits': ['bms', 'protection', 'overcharge protection', 'safety features'],
  'airline approved': ['flight safe', 'airline safe', 'faa approved'],
  'grip type': ['stand type', 'clamp type', 'holder type'],
  'primary use': ['application', 'intended use', 'use case'],
  material: ['build material', 'construction material'],
  // --- Phase 1 canonical taxonomy names (absorbed old names as aliases) ---
  'codecs / formats': [
    'codec',
    'codecs',
    'codec options',
    'video format',
    'recording format',
    'compression',
    'video codec',
    'raw recording',
    'prores',
  ],
  'media / card slots': [
    'memory card slots',
    'card slots',
    'media slots',
    'card types supported',
    'supported cards',
    'cfexpress type',
    'recording media',
  ],
  'audio type': ['mic type', 'microphone type', 'system type', 'transducer'],
  connectivity: ['connector', 'output connector', 'connector type', 'connection', 'inputs'],
  'bit depth / sample rate': ['bit depth', 'sample rate', 'audio resolution'],
  'power source': [
    'power requirements',
    'power input',
    'battery compatible',
    'battery mount',
    'ac input',
    'usb power',
  ],
  'inputs / outputs': [
    'hdmi input',
    'hdmi output',
    'sdi input',
    'sdi output',
    'video input',
    'video output',
    'i/o',
    'loop out',
  ],
  'monitoring tools': [
    'waveform',
    'false color',
    'focus peaking',
    'zebras',
    'lut support',
    'exposure tools',
    'scopes',
  ],
  'hdr support': ['hdr', 'hdr formats', 'hdr10', 'hlg', 'dolby vision'],
  'max output': ['max discharge', 'max continuous draw', 'max draw', 'peak draw'],
  outputs: ['d-tap outputs', 'usb outputs', 'dc outputs', 'output ports', 'ports'],
  charging: ['charge time', 'charging time', 'recharge time', 'charge current', 'charger type'],
  'height range': ['max height', 'maximum height', 'min height', 'minimum height', 'extended height'],
  'folded length': ['folded dimensions', 'collapsed length', 'folded size', 'closed length'],
  'bowl size': ['bowl', 'half ball', 'ball diameter'],
  'quick release': ['quick release plate', 'plate type', 'qr plate'],
  'axes / modes': ['axis count', 'axes', 'follow modes', 'gimbal modes', 'stabilization modes'],
  'travel / track length': [
    'track length',
    'travel',
    'travel distance',
    'rail length',
    'extension range',
  ],
  timecode: ['tc', 'timecode support', 'bluetooth timecode', 'jam sync'],
  channels: ['channel count', 'number of channels', 'transmitters'],
  'camera sensor': ['main camera', 'imaging sensor', 'camera'],
  'obstacle sensing': ['obstacle avoidance', 'sensing system', 'apas', 'obstacle sensors'],
  'max transmission range': [
    'transmission range',
    'transmission',
    'video transmission',
    'max range',
  ],
  'flight time': ['max flight time', 'hover time'],
  'takeoff weight': ['max takeoff weight', 'aircraft weight'],
  'format coverage': ['image circle', 'lens format coverage', 'sensor coverage'],
  'anamorphic squeeze': ['squeeze', 'squeeze factor', 'anamorphic factor'],
  'color mode': ['rgbww', 'bi-color', 'bicolor', 'hsi', 'color control'],
  dmx: ['dmx512', 'dmx channels', 'crmx', 'lumenradio'],
  'pin size': ['baby pin', 'junior pin', 'spud size', 'receiver size'],
  'grip head / jaw': ['grip head', 'jaw capacity', 'clamp opening'],
  fabric: ['fabric type', 'fabric material', 'diffusion'],
  'sections / risers': ['sections', 'risers', 'number of sections'],
  'height / length range': [
    'min length',
    'max length',
    'extended length',
    'collapsed length',
    'length range',
  ],
  'max load': ['max load capacity', 'load capacity', 'weight capacity'],
  'filter type': ['nd', 'variable nd', 'polarizer', 'filter density', 'nd stops'],
  'speed class': ['uhs', 'uhs speed class', 'video speed class', 'v30', 'v60', 'v90'],
  'min sustained write': ['minimum sustained write', 'sustained write', 'min sequential write', 'vpg'],
  durability: ['shock resistant', 'waterproof', 'x-ray proof', 'ip rating', 'rugged'],
  endurance: ['tbw', 'write endurance'],
  counterbalance: ['counter balance', 'cb range'],
  'connector / cable': ['cable type', 'cable length', 'connector type a', 'connector type b'],
  mounting: ['mounting points', 'mounting type', 'nato rail', 'cold shoe', 'arri rosette'],
};

// Named confidence thresholds (replaces magic numbers)
export const CONFIDENCE = {
  DIRECT_MATCH: 85,
  ALIAS_EXPANSION: 97,
  CONTAINMENT_HIGH: 85,
  CONTAINMENT_LOW: 80,
  FUZZY_MINIMUM: 50,
  FUZZY_ALIAS_MINIMUM: 55,
  FUZZY_CAP: 92,
  COMMUNITY_BASE: 55,
  COMMUNITY_MAX: 75,
  CONFLICT_DIFF_THRESHOLD: 15,
  MERGE_RANGE: 10,
  SINGLE_LONG_WORD: 55,
  SINGLE_MEDIUM_WORD: 50,
};

// Unit conversions for normalization
// NOTE: patterns must NOT use the 'g' flag — .match(regex) with 'g' drops capturing groups
export const UNIT_CONVERSIONS = {
  in_to_mm: { pattern: /([\d.]+)\s*(?:in(?:ch(?:es)?)?|")\b/i, factor: 25.4, toUnit: 'mm' },
  mm_to_in: { pattern: /([\d.]+)\s*mm\b/i, factor: 1 / 25.4, toUnit: 'in' },
  lb_to_g: { pattern: /([\d.]+)\s*(?:lbs?|pounds?)\b/i, factor: 453.592, toUnit: 'g' },
  oz_to_g: { pattern: /([\d.]+)\s*(?:oz|ounces?)\b/i, factor: 28.3495, toUnit: 'g' },
  f_to_c: {
    pattern: /([\d.]+)\s*°?\s*F\b/i,
    fn: (v) => (((v - 32) * 5) / 9).toFixed(0),
    toUnit: '°C',
  },
};

// Known value ranges for field validation
export const VALUE_RANGES = {
  // Weight is stored in oz/lb since the 2026-08-17 canonical taxonomy — the
  // old bare `max: 100` assumed kg and flagged a 7 lb tripod (112 oz) while
  // passing genuinely absurd oz values. Convert whatever unit was pasted.
  Weight: {
    pattern: /[\d.]+/,
    checkFn: (value) => {
      const m = String(value).match(/([\d.]+)\s*(kg|kgs|g|lbs?|pounds?|oz|ounces?)?\b/i);
      if (!m) return true;
      const num = parseFloat(m[1]);
      if (isNaN(num)) return true;
      const unit = (m[2] || 'oz').toLowerCase();
      const grams = unit.startsWith('kg')
        ? num * 1000
        : unit === 'g'
          ? num
          : unit.startsWith('lb') || unit.startsWith('pound')
            ? num * 453.592
            : num * 28.3495;
      return grams <= 100000;
    },
    warn: 'Weight over 100 kg / 220 lb — verify value',
  },
  'Focal Length': {
    pattern: /[\d.]+/,
    max: 2000,
    unit: 'mm',
    warn: 'Focal length over 2000mm — verify value',
  },
  'Maximum Aperture': {
    pattern: /f?\/?(\d+\.?\d*)/,
    group: 1,
    min: 0.7,
    max: 64,
    warn: 'Unusual aperture value — verify',
  },
  'Minimum Aperture': {
    pattern: /f?\/?(\d+\.?\d*)/,
    group: 1,
    min: 0.7,
    max: 128,
    warn: 'Unusual aperture value — verify',
  },
  'Power Output': {
    pattern: /[\d.]+/,
    max: 20000,
    unit: 'W',
    warn: 'Power over 20kW — verify value',
  },
  'Screen Size': {
    pattern: /[\d.]+/,
    max: 100,
    unit: 'inches',
    warn: 'Screen size over 100" — verify value',
  },
  'Battery Life': {
    pattern: /[\d.]+/,
    max: 10000,
    warn: 'Unusually high battery life — verify value',
  },
  'ISO Range': {
    pattern: /[\d,]+/,
    checkFn: (v) => {
      const n = parseInt(v.replace(/,/g, ''));
      return n > 0 && n <= 10000000;
    },
    warn: 'ISO value out of expected range',
  },
};

// Generic words excluded from single-word alias matching
export const GENERIC_WORDS = new Set([
  'type',
  'size',
  'rate',
  'range',
  'mode',
  'with',
  'from',
  'output',
  'input',
  'total',
  'number',
  'system',
  'included',
  'support',
  'supported',
  'compatible',
  'maximum',
  'minimum',
  'speed',
  'level',
  'control',
  'depth',
  'life',
  'time',
  'capacity',
  'power',
  'count',
  'body',
  'recording',
  'card',
  'cable',
  'mount',
  'class',
  'ratio',
  'material',
  'format',
  'angle',
  'length',
  'height',
  'weight',
  'draw',
  'plate',
  'points',
  'slots',
  'display',
  'assist',
  'color',
  'load',
  'adjustment',
  'rotation',
  'position',
  'noise',
  'temp',
]);

// CDN load timeouts
export const CDN_TIMEOUT_PDF_MS = 15000;
export const CDN_TIMEOUT_OCR_MS = 30000;
